IF EXISTS(SELECT * FROM SYSOBJECTS WHERE XTYPE='P' AND [NAME]='USP_EXTRACTION_INWARD_EXCEL_FILE')
BEGIN
	DROP PROCEDURE USP_EXTRACTION_INWARD_EXCEL_FILE
END

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- AUTHOR	  :	PRIYANKA B.
-- CREATE DATE: 15/01/2018
-- DESCRIPTION:	THIS STORED PROCEDURE IS USEFUL TO GENERATE INWARD EXCEL EXTRACTION FILE.
-- MODIFIED BY: 
-- MODIFY DATE: 
-- REMARK:
-- =============================================

CREATE PROCEDURE  [dbo].[USP_EXTRACTION_INWARD_EXCEL_FILE]
@LSTARTDATE  SMALLDATETIME,@LENDDATE SMALLDATETIME
AS

--Purchase & Import Purchase
SELECT * INTO #SELF FROM (SELECT  H.Entry_ty, H.Tran_cd,Cons_ac_name =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else Cons_ac.ac_name end ) else( case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.mailname else  seller_ac.ac_name end) end )
,Cons_gstin = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.GSTIN,'') = '' THEN '' ELSE Cons_sp.GSTIN END ) else (CASE WHEN ISNULL(Cons_ac.GSTIN,'') = '' THEN '' ELSE Cons_ac.GSTIN  END )	end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(seller_sp.GSTIN,'') = ''  then '' else seller_sp.GSTIN end) else  (CASE WHEN ISNULL(seller_ac.GSTIN,'')= '' THEN '' ELSE seller_ac.GSTIN END) end) end),seller_gstin =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.GSTIN else  seller_ac.GSTIN end)
,pos_std_cd =h.GSTSCODE,pos = h.gststate ,Cons_pos =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.state else  Cons_ac.state end),seller_pos =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.state else  seller_ac.state  end),(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno ,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt,h.beno,h.bedt,Cons_LocId=Isnull(Cons_sp.Location_Id,''),h.net_amt
FROM PTMAIN H LEFT OUTER JOIN shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id ) LEFT OUTER JOIN	ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id) LEFT OUTER JOIN	shipto seller_sp ON (seller_sp.ac_id = h.Ac_id and seller_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN	ac_mast seller_ac ON (h.Ac_id = seller_ac.ac_id) WHERE H.entry_ty IN ('PT','P1') AND (Cons_ac.supp_type='Unregistered' or Seller_ac.supp_type='Unregistered')
UNION ALL
SELECT  H.Entry_ty, H.Tran_cd,Cons_ac_name =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else Cons_ac.ac_name end ) else( case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.mailname else  seller_ac.ac_name end) end ),Cons_gstin = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.GSTIN,'') = '' THEN '' ELSE Cons_sp.GSTIN END ) else (CASE WHEN ISNULL(Cons_ac.GSTIN,'') = '' THEN '' ELSE Cons_ac.GSTIN  END ) end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(seller_sp.GSTIN,'') = ''  then '' else seller_sp.GSTIN end ) 
else (CASE WHEN ISNULL(seller_ac.GSTIN,'')= '' THEN '' ELSE seller_ac.GSTIN END) end) end),seller_gstin =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.GSTIN  else  seller_ac.GSTIN end),pos_std_cd =H.GSTSCODE,pos = H.GSTState ,Cons_pos =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.state else  Cons_ac.state end),seller_pos =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.state else  seller_ac.state  end)
,(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno ,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt,'' as beno, '' as bedt,Cons_LocId=Isnull(Cons_sp.Location_Id,''),h.net_amt FROM EPMAIN H LEFT OUTER JOIN shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id ) LEFT OUTER JOIN ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id) LEFT OUTER JOIN shipto seller_sp ON (seller_sp.ac_id = h.Ac_id and seller_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN ac_mast seller_ac ON (h.Ac_id = seller_ac.ac_id) Where H.entry_ty in ('E1') AND (Cons_ac.supp_type='Unregistered' or Seller_ac.supp_type='Unregistered'))AA
SELECT mCGST_PER = CAST(0 AS NUMERIC(7,2)),mSGST_PER = CAST(0 AS NUMERIC(7,2)),mIGST_PER = CAST(0 AS NUMERIC(7,2)),* INTO #INTEMP_1 FROM (
/*Original details for Self Invoice*/
SELECT H.Entry_ty, H.Tran_cd, D.ITSERIAL, H.INV_NO, H.DATE,D .IT_CODE,D.QTY,isnull(d.u_asseamt,0) AS Taxableamt,isnull(d.CGST_PER,0) as CGST_PER,isnull(D.CGST_AMT,0) as CGST_AMT,isnull(d.SGST_PER,0) as SGST_PER ,isnull(D.SGST_AMT,0) as SGST_AMT,isnull(d.IGST_PER,0) as IGST_PER,isnull(D.IGST_AMT,0) as IGST_AMT	,ORG_INVNO='', ORG_DATE='',isnull(D.CGSRT_AMT,0) as CGSRT_AMT,ISNULL(D.SGSRT_AMT,0) as SGSRT_AMT
,isnull(D.IGSRT_AMT,0) as IGSRT_AMT ,isnull(D.GRO_AMT,0) as GRO_AMT,isnull(H.net_amt,0) as net_amt,D.CCESSRATE as Cess_per,isnull(D.COMPCESS,0) as Cess_amt,isnull(D.COMRPCESS,0) As CessRT_amt,'Taxable' as LineRule,h.inv_sr ,h.l_yn,IT.s_unit as uqc ,IT.IT_NAME,(CASE WHEN IT.Isservice = 0 THEN 'Goods' WHEN IT.Isservice = 1 THEN 'Services' ELSE '' END) AS Isservice,HSNCODE = (CASE WHEN IT.Isservice = 0 THEN IT.HSNCODE  WHEN IT.Isservice = 1 THEN IT.ServTCode ELSE '' END),'' as RevCharge
,'' AS AGAINSTGS,AmendDate = '',s.Cons_ac_name,Cons_SUPP_TYPE = 'Unregistered',seller_SUPP_TYPE = 'Unregistered',Cons_st_type ='',seller_st_type =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end),s.Cons_gstin,s.seller_gstin,pos_std_cd =h.GSTSCODE,pos = h.gststate,s.Cons_pos,s.seller_pos,Cons_PANNO = Cons_ac.i_tax
,seller_PANNO = seller_ac.i_tax,(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt,H.TRANSTATUS,gstype =(CASE WHEN ISNULL(D.ECredit,0) = 1 THEN (case when IT.Isservice = 0  then (case when IT.type = 'Machinery/Stores' then 'Capital Goods' else 'Input Goods' end) else 'Input Services' end) else 'Ineligible for ITC' END)
,AVL_ITC = ISNULL(D.ECredit,0), s.beno , s.BEDT,d.gstrate,'' as portcode,'Purchases' as TransType,H.U_IMPORM as TransSubType	,Reason = '',Cons_shiptoId=(case WHEN isnull(H.scons_id, 0) > 0 then  isnull(Cons_sp.shipto_id,0) else 0 end),s.Cons_LocId,ITC_Date=case when isnull(H.u_itcdate,'')>1900 then isnull(H.u_itcdate,'') else isnull(H.date,'') end,Cons_uid = (case WHEN isnull(H.scons_id, 0) > 0 then  isnull(Cons_sp.UID,'') else isnull(Cons_ac.UID,'')  end)
,Supp_Desc = case when isnull(cast(IT.it_desc as varchar(4000)),'')<>'' then cast(IT.it_desc as varchar(4000)) else '' end,HSN_Desc = '',IsSerGoods = IT.Isservice,ItType = rtrim(ltrim(IT.Type)) ,iigst_amt=((ISNULL(D.igst_amt,0)+ ISNULL(D.IGSRT_AMT,0))-ISNULL(b.iigst_amt,0)),icgst_amt=((ISNULL(D.cgst_amt,0) + ISNULL(D.CGSRT_AMT,0)) - ISNULL(b.icgst_amt,0))
,isGST_AMT=((isnull(D.sGST_AMT,0)+ isnull(D.SGSRT_AMT,0))-isnull(b.isGST_AMT,0)),ICESS_AMT = ((isnull(D.COMPCESS,0)+ isnull(D.COMRPCESS,0)) - isnull(B.ICESS_AMT,0)),Gs_type = (case when h.againstgs ='Goods' then 'Goods' when h.againstgs = 'Services' then 'Services' END),'' as expotype,'' as OrgTransType,'' as OrgGstin
FROM STMAINAM H	left outer JOIN	STITEMAM D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD)	left outer JOIN	IT_MAST IT ON (D .IT_CODE = IT.IT_CODE) LEFT OUTER JOIN	shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id ) LEFT OUTER JOIN	ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id) LEFT OUTER JOIN	shipto seller_sp ON (seller_sp.ac_id = h.Ac_id and seller_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN	ac_mast seller_ac ON (h.Ac_id = seller_ac.ac_id)
left outer join epayment b on (D.Tran_cd = b.tran_cd  and D.Entry_ty =b.entry_ty and d.ITSERIAL =b.itserial) inner join rcmdetail rcm on (D.Entry_ty=rcm.Entry_ty and D.Tran_cd=rcm.Tran_cd and D.Itserial=rcm.itserial) inner join #self s on (rcm.pentry_ty=s.entry_ty and rcm.ptran_cd=s.tran_cd) WHERE H.entry_ty ='UB'
UNION ALL
/*Amendment details for Self Invoice*/
SELECT  H.Entry_ty, H.Tran_cd, D.ITSERIAL, H.INV_NO, H.Date,D .IT_CODE,D.QTY,isnull(d.u_asseamt,0) AS Taxableamt,isnull(d.CGST_PER,0) as CGST_PER,isnull(D.CGST_AMT,0) as CGST_AMT,isnull(d.SGST_PER,0) as SGST_PER,isnull(D.SGST_AMT,0) as SGST_AMT,isnull(d.IGST_PER,0) as IGST_PER,isnull(D.IGST_AMT,0) as IGST_AMT,ORG_INVNO=H.pinvno, ORG_DATE=H.pinvdt,isnull(D.CGSRT_AMT,0) as CGSRT_AMT,ISNULL(D.SGSRT_AMT,0) as SGSRT_AMT,isnull(D.IGSRT_AMT,0) as IGSRT_AMT
,isnull(D.GRO_AMT,0) as GRO_AMT,isnull(h.net_amt,0) as net_amt,D.CCESSRATE as Cess_per,isnull(D.COMPCESS,0) as Cess_amt,isnull(D.COMRPCESS,0) As CessRT_amt,'Taxable' as LineRule,h.inv_sr,h.l_yn,IT.s_unit as uqc,IT.IT_NAME,(CASE WHEN IT.Isservice = 0 THEN 'Goods' WHEN IT.Isservice = 1 THEN 'Services' ELSE '' END) AS Isservice,HSNCODE = (case when IT.Isservice=0 then IT.HSNCODE else IT.ServTCode end),'' as RevCharge,'' AS AGAINSTGS
,AmendDate = (case when DATEDIFF(MM,H.DATE,H.AmendDAte) > 0 then h.AmendDate else ''  end ),s.Cons_ac_name,Cons_SUPP_TYPE = 'Unregistered',seller_SUPP_TYPE = 'Unregistered',Cons_st_type ='',seller_st_type =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end),s.Cons_gstin,s.seller_gstin,pos_std_cd =h.GSTSCODE,pos = h.gststate,s.Cons_pos,s.seller_pos,Cons_PANNO = Cons_ac.i_tax
,seller_PANNO = seller_ac.i_tax,(case when amd.pinvno <> ''  then  amd.pinvno else H.INV_NO end) as pinvno,(case when amd.pinvdt <> ''  then  amd.pinvdt else H.date end) as pinvdt,H.TRANSTATUS,gstype =(CASE WHEN ISNULL(D.ECredit,0) = 1 THEN (case when IT.Isservice = 0  then (case when IT.type = 'Machinery/Stores' then 'Capital Goods' else 'Input Goods' end) else 'Input Services' end) else 'Ineligible for ITC' END)
,AVL_ITC = ISNULL(D.ECredit,0), s.beno ,s.BEDT,d.gstrate,'' as portcode,'Purchases' as TransType,H.U_IMPORM as TransSubType,Reason = '',Cons_shiptoId=(case WHEN isnull(H.scons_id, 0) > 0 then  isnull(Cons_sp.shipto_id,0) else 0 end),s.Cons_LocId,ITC_Date=case when isnull(H.u_itcdate,'')>1900 then isnull(H.u_itcdate,'') else isnull(H.AmendDate,'') end,Cons_uid = (case WHEN isnull(H.scons_id, 0) > 0 then  isnull(Cons_sp.UID,'') else isnull(Cons_ac.UID,'')  end)
,Supp_Desc = case when isnull(cast(it.it_desc as varchar(4000)),'')<>'' then cast(it.it_desc as varchar(4000)) else '' end,HSN_Desc = '',IsSerGoods = IT.Isservice,ItType = rtrim(ltrim(IT.Type)),iigst_amt=((ISNULL(D.igst_amt,0)+ ISNULL(D.IGSRT_AMT,0))-ISNULL(b.iigst_amt,0)),icgst_amt=((ISNULL(D.cgst_amt,0) + ISNULL(D.CGSRT_AMT,0)) - ISNULL(b.icgst_amt,0)),isGST_AMT=((isnull(D.sGST_AMT,0)+ isnull(D.SGSRT_AMT,0))-isnull(b.isGST_AMT,0)),ICESS_AMT = ((isnull(D.COMPCESS,0)+ isnull(D.COMRPCESS,0)) - isnull(B.ICESS_AMT,0))
,Gs_type = (case when h.againstgs ='Goods' then 'Goods' when h.againstgs = 'Services' then 'Services' END),'' as expotype,'Purchases' as OrgTransType,(case WHEN isnull(H.sAc_id, 0) > 0 then seller_sp.GSTIN else seller_ac.GSTIN end) as OrgGstin FROM STMAIN H left outer JOIN STITEM D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) left outer JOIN	IT_MAST IT ON (D .IT_CODE = IT.IT_CODE) LEFT OUTER JOIN	shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id )
LEFT OUTER JOIN	ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id) LEFT OUTER JOIN	shipto seller_sp ON (seller_sp.ac_id = h.Ac_id and seller_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN	ac_mast seller_ac ON (h.Ac_id = seller_ac.ac_id) left outer join epayment b on (D.Tran_cd = b.tran_cd  and D.Entry_ty =b.entry_ty and d.ITSERIAL =b.itserial) inner join rcmdetail rcm on (D.Entry_ty=rcm.Entry_ty and D.Tran_cd=rcm.Tran_cd and D.Itserial=rcm.itserial) inner join #self s on (rcm.pentry_ty=s.entry_ty and rcm.ptran_cd=s.tran_cd)
LEFT OUTER JOIN STMAINAM AMD ON (H.entry_ty =AMD.ENTRY_TY AND H.Tran_cd =AMD.TRAN_CD) WHERE H.entry_ty ='UB'
UNION ALL
/*Original details of Purchase & Import Purchase*/
SELECT  H.Entry_ty, H.Tran_cd, D.ITSERIAL, H.INV_NO, H.DATE,D.IT_CODE,D.QTY,isnull(d.u_asseamt,0) AS Taxableamt,isnull(d.CGST_PER,0) as CGST_PER,isnull(D.CGST_AMT,0) as CGST_AMT,isnull(d.SGST_PER,0) as SGST_PER,isnull(D.SGST_AMT,0)as SGST_AMT,isnull(d.IGST_PER,0) as IGST_PER,isnull(D.IGST_AMT,0)as IGST_AMT,ORG_INVNO='', ORG_DATE='',isnull(D.CGSRT_AMT,0) as CGSRT_AMT, isnull(D.SGSRT_AMT,0) as SGSRT_AMT
,isnull(D.IGSRT_AMT,0) as IGSRT_AMT,isnull(D.GRO_AMT,0) as GRO_AMT,isnull(h.net_amt,0)as net_amt,D.CCESSRATE as Cess_per,isnull(D.COMPCESS,0) as Cess_amt,isnull(D.COMRPCESS,0) As CessRT_amt,D.LineRule,h.inv_sr,h.l_yn,IT.s_unit as uqc,IT.IT_NAME,(CASE WHEN IT.Isservice = 0 THEN 'Goods' WHEN IT.Isservice = 1 THEN 'Services' ELSE '' END) AS Isservice, HSNCODE = (case when Isservice=0 then IT.HSNCODE else IT.ServTCode end),'' as RevCharge,'' AS AGAINSTGS,AmendDate = ''
,Cons_ac_name =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else  Cons_ac.ac_name end),Cons_SUPP_TYPE =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.SUPP_TYPE else Cons_ac.SUPP_TYPE end ) else( case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end) end )
,seller_SUPP_TYPE =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end),Cons_st_type =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.st_type else  Cons_ac.st_type end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end) end),seller_st_type =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end)
,Cons_gstin = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.GSTIN,'') = '' THEN '' ELSE Cons_sp.GSTIN END ) else (CASE WHEN ISNULL(Cons_ac.GSTIN,'') = '' THEN '' ELSE Cons_ac.GSTIN  END ) end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(seller_sp.GSTIN,'') = ''  then '' else seller_sp.GSTIN end ) else  (CASE WHEN ISNULL(seller_ac.GSTIN,'')= '' THEN '' ELSE seller_ac.GSTIN END) end) end)
,seller_gstin =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.GSTIN else  seller_ac.GSTIN end),pos_std_cd =h.GSTSCODE,pos = h.gststate,Cons_pos =(case WHEN isnull(H.scons_id, 0) > 0 then Cons_sp.state else Cons_ac.state end),seller_pos =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.state else  seller_ac.state  end),Cons_PANNO = Cons_ac.i_tax,seller_PANNO = seller_ac.i_tax	,(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno
,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt,H.TRANSTATUS,gstype =(CASE WHEN ISNULL(D.ECredit,0) = 1 THEN (case when IT.Isservice = 0  then (case when IT.type = 'Machinery/Stores' then 'Capital Goods' else 'Input Goods' end) else 'Input Services' end) else 'Ineligible for ITC' END) ,AVL_ITC = ISNULL(D.ECredit,0), beno , BEDT ,d.gstrate ,portcode=Left(isnull(H.portcode,''),6),'Purchases' as TransType,H.U_IMPORM as TransSubType,Reason = '',Cons_shiptoId=(case WHEN isnull(H.scons_id, 0) > 0 then  isnull(Cons_sp.shipto_id,0) else 0 end)
,Cons_LocId=Isnull(Cons_sp.Location_Id,''),ITC_Date=case when isnull(H.u_itcdate,'')>1900 then isnull(H.u_itcdate,'') else isnull(H.date,'') end,Cons_uid = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.UID,'') <> '' THEN Cons_sp.UID ELSE '' END ) else (CASE WHEN ISNULL(Cons_ac.UID,'') <> '' THEN Cons_ac.UID  ELSE '' END )	end) else (case WHEN isnull(H.sAc_id, 0) > 0 then (CASE When isnull(seller_sp.UID,'') <> ''  then seller_sp.UID else '' end ) 
else  (CASE WHEN ISNULL(seller_ac.UID,'') <> '' THEN seller_ac.UID ELSE '' END) end) end),Supp_Desc = case when isnull(cast(it.it_desc as varchar(4000)),'')<>'' then cast(it.it_desc as varchar(4000)) else '' end,HSN_Desc = '',IsSerGoods = IT.Isservice,ItType = rtrim(ltrim(IT.Type)),iigst_amt=((ISNULL(D.igst_amt,0)+ ISNULL(D.IGSRT_AMT,0))-ISNULL(b.iigst_amt,0)),icgst_amt=((ISNULL(D.cgst_amt,0) + ISNULL(D.CGSRT_AMT,0)) - ISNULL(b.icgst_amt,0)),isGST_AMT=((isnull(D.sGST_AMT,0)+ isnull(D.SGSRT_AMT,0))-isnull(b.isGST_AMT,0))
,ICESS_AMT = ((isnull(D.COMPCESS,0)+ isnull(D.COMRPCESS,0)) - isnull(B.ICESS_AMT,0)),Gs_type = 'Goods',h.expotype,'' as OrgTransType,'' as OrgGstin FROM PTMAINAM H LEFT OUTER JOIN	PTITEMAM D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) LEFT OUTER JOIN	IT_MAST IT ON (D .IT_CODE = IT.IT_CODE) LEFT OUTER JOIN	shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id )
LEFT OUTER JOIN	ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id) LEFT OUTER JOIN	shipto seller_sp ON (seller_sp.ac_id = h.Ac_id and seller_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN ac_mast seller_ac ON (h.Ac_id = seller_ac.ac_id) left outer join epayment b on (D.Tran_cd = b.tran_cd  and D.Entry_ty =b.entry_ty and d.ITSERIAL =b.itserial) WHERE H.entry_ty IN('PT','P1') AND (Cons_ac.supp_type<>'Unregistered' or Seller_ac.supp_type<>'Unregistered') OR (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else  Cons_ac.ac_name end)='CANCELLED.'
UNION ALL
/*Amendment details of Purchase & Import Purchase*/
SELECT  H.Entry_ty, H.Tran_cd, D.ITSERIAL, H.INV_NO, H.Date,D.IT_CODE,D.QTY,isnull(d.u_asseamt,0) AS Taxableamt,isnull(d.CGST_PER,0) as CGST_PER,isnull(D.CGST_AMT,0) as CGST_AMT,isnull(d.SGST_PER,0) as SGST_PER,isnull(D.SGST_AMT,0)as SGST_AMT,isnull(d.IGST_PER,0) as IGST_PER,isnull(D.IGST_AMT,0)as IGST_AMT
--,ORG_INVNO=H.pinvno,ORG_DATE=H.pinvdt   --Commented by Priyanka B on 15012018 for Bug-30832
,ORG_INVNO=(case when isnull(H.amenddate,'')<>'' then amd.pinvno else '' end),ORG_DATE=(case when isnull(H.amenddate,'')<>'' then amd.pinvdt else '' end)   --Modified by Priyanka B on 15012018 for Bug-30832
,isnull(D.CGSRT_AMT,0) as CGSRT_AMT, isnull(D.SGSRT_AMT,0) as SGSRT_AMT,isnull(D.IGSRT_AMT,0) as IGSRT_AMT,isnull(D.GRO_AMT,0) as GRO_AMT,isnull(h.net_amt,0)as net_amt,D.CCESSRATE as Cess_per,isnull(D.COMPCESS,0) as Cess_amt,isnull(D.COMRPCESS,0) As CessRT_amt,D.LineRule,h.inv_sr,h.l_yn,IT.s_unit as uqc,IT.IT_NAME,(CASE WHEN IT.Isservice = 0 THEN 'Goods' WHEN IT.Isservice = 1 THEN 'Services' ELSE '' END) AS Isservice,HSNCODE = (case when Isservice=0 then IT.HSNCODE else IT.ServTCode end),'' as RevCharge,'' AS AGAINSTGS,AmendDate = (case when DATEDIFF(MM,H.DATE,H.AmendDAte) > 0 then h.AmendDate else ''  end )
,Cons_ac_name =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else  Cons_ac.ac_name end),Cons_SUPP_TYPE =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.SUPP_TYPE else Cons_ac.SUPP_TYPE end ) else( case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end) end ),seller_SUPP_TYPE =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end),Cons_st_type =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.st_type
else Cons_ac.st_type end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end) end),seller_st_type =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end),Cons_gstin = (case when seller_ac.i_tax=Cons_ac.i_tax then	(case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.GSTIN,'') = '' THEN '' ELSE Cons_sp.GSTIN END ) else (CASE WHEN ISNULL(Cons_ac.GSTIN,'') = '' THEN '' ELSE Cons_ac.GSTIN  END ) end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(seller_sp.GSTIN,'') = ''  then '' else seller_sp.GSTIN end ) else  (CASE WHEN ISNULL(seller_ac.GSTIN,'')= '' THEN '' ELSE seller_ac.GSTIN END)
end) end),seller_gstin =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.GSTIN else  seller_ac.GSTIN end),pos_std_cd =h.GSTSCODE,pos = h.gststate ,Cons_pos =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.state else  Cons_ac.state end),seller_pos =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.state else  seller_ac.state  end),Cons_PANNO = Cons_ac.i_tax ,seller_PANNO = seller_ac.i_tax,(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt,H.TRANSTATUS,gstype =(CASE WHEN ISNULL(D.ECredit,0) = 1 THEN (case when IT.Isservice = 0  then (case when IT.type = 'Machinery/Stores'
then 'Capital Goods' else 'Input Goods' end) else 'Input Services' end) else 'Ineligible for ITC' END),AVL_ITC = ISNULL(D.ECredit,0), H.beno , H.BEDT ,d.gstrate ,portcode=Left(isnull(H.portcode,''),6),'Purchases' as TransType,H.U_IMPORM as TransSubType,Reason = '',Cons_shiptoId=(case WHEN isnull(H.scons_id, 0) > 0 then isnull(Cons_sp.shipto_id,0) else 0 end) ,Cons_LocId=Isnull(Cons_sp.Location_Id,''),ITC_Date=case when isnull(H.u_itcdate,'')>1900 then isnull(H.u_itcdate,'') else isnull(H.AmendDate,'') end,Cons_uid = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0
then (CASE WHEN ISNULL(Cons_sp.UID,'') <> '' THEN Cons_sp.UID ELSE '' END ) else (CASE WHEN ISNULL(Cons_ac.UID,'') <> '' THEN Cons_ac.UID  ELSE '' END ) end) else (case WHEN isnull(H.sAc_id, 0) > 0 then (CASE When isnull(seller_sp.UID,'') <> ''  then seller_sp.UID else '' end ) else  (CASE WHEN ISNULL(seller_ac.UID,'') <> '' THEN seller_ac.UID ELSE '' END) end) end),Supp_Desc = case when isnull(cast(it.it_desc as varchar(4000)),'')<>'' then cast(it.it_desc as varchar(4000)) else '' end,HSN_Desc = '',IsSerGoods = IT.Isservice,ItType = rtrim(ltrim(IT.Type)),iigst_amt=((ISNULL(D.igst_amt,0)+ ISNULL(D.IGSRT_AMT,0))-ISNULL(b.iigst_amt,0)),icgst_amt=((ISNULL(D.cgst_amt,0) + ISNULL(D.CGSRT_AMT,0)) - ISNULL(b.icgst_amt,0))
,isGST_AMT=((isnull(D.sGST_AMT,0)+ isnull(D.SGSRT_AMT,0))-isnull(b.isGST_AMT,0)),ICESS_AMT = ((isnull(D.COMPCESS,0)+ isnull(D.COMRPCESS,0)) - isnull(B.ICESS_AMT,0)),Gs_type = 'Goods',h.expotype
--,'Purchases' as OrgTransType  --Commented by Priyanka B on 15012018 for Bug-30832
,(case when isnull(H.amenddate,'')<>'' then 'Purchases' else '' end) as OrgTransType  --Modified by Priyanka B on 15012018 for Bug-30832
,H.Oldgstin as OrgGstin FROM PTMAIN H LEFT OUTER JOIN	PTITEM D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) LEFT OUTER JOIN IT_MAST IT ON (D .IT_CODE = IT.IT_CODE) LEFT OUTER JOIN	shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id ) LEFT OUTER JOIN	ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id) LEFT OUTER JOIN	shipto seller_sp ON (seller_sp.ac_id = h.Ac_id and seller_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN	ac_mast seller_ac ON (h.Ac_id = seller_ac.ac_id) 
left outer join epayment b on (D.Tran_cd = b.tran_cd  and D.Entry_ty =b.entry_ty and d.ITSERIAL =b.itserial) LEFT OUTER JOIN PTMAINAM AMD ON (H.entry_ty =AMD.ENTRY_TY AND H.Tran_cd =AMD.TRAN_CD ) WHERE H.entry_ty IN('PT','P1') AND (Cons_ac.supp_type<>'Unregistered' or Seller_ac.supp_type<>'Unregistered')
UNION ALL
--Original details for Purchase Return
SELECT  H.Entry_ty, H.Tran_cd, D.ITSERIAL, H.INV_NO, H.DATE,D.IT_CODE,D.QTY,isnull(d.u_asseamt,0) AS Taxableamt,isnull(d.CGST_PER,0) as CGST_PER,isnull(D.CGST_AMT,0) as CGST_AMT,isnull(d.SGST_PER,0) as SGST_PER,isnull(D.SGST_AMT,0)as SGST_AMT,isnull(d.IGST_PER,0) as IGST_PER,isnull(D.IGST_AMT,0) as IGST_AMT,d.sbillno as ORG_INVNO,d.sbdate as ORG_DATE,isnull(D.CGSRT_AMT,0) as CGSRT_AMT, isnull(D.SGSRT_AMT,0) as SGSRT_AMT,isnull(D.IGSRT_AMT,0) as IGSRT_AMT,isnull(D.GRO_AMT,0) as GRO_AMT,isnull(h.net_amt,0) as net_amt,D.CCESSRATE as Cess_per,isnull(D.COMPCESS,0) as Cess_amt,isnull(D.COMRPCESS,0) As CessRT_amt,D.LineRule,h.inv_sr,h.l_yn	,IT.s_unit as uqc ,IT.IT_NAME
,(CASE WHEN IT.Isservice = 0 THEN 'Goods' WHEN IT.Isservice = 1 THEN 'Services' ELSE '' END) AS Isservice,HSNCODE = (case when Isservice=0 then IT.HSNCODE else IT.ServTCode end),'' as RevCharge,'' AS AGAINSTGS,AmendDate = '',Cons_ac_name =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else  Cons_ac.ac_name end),Cons_SUPP_TYPE =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.SUPP_TYPE else Cons_ac.SUPP_TYPE end ) else( case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else seller_ac.SUPP_TYPE end) end ),seller_SUPP_TYPE =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end)
,Cons_st_type =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.st_type else  Cons_ac.st_type end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end) end),seller_st_type =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end),Cons_gstin = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.GSTIN,'') = '' THEN '' ELSE Cons_sp.GSTIN END ) else (CASE WHEN ISNULL(Cons_ac.GSTIN,'') = '' THEN '' ELSE Cons_ac.GSTIN  END ) end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(seller_sp.GSTIN,'') = ''  then ''
else seller_sp.GSTIN end ) else  (CASE WHEN ISNULL(seller_ac.GSTIN,'')= '' THEN '' ELSE seller_ac.GSTIN END) end) end),seller_gstin =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.GSTIN else  seller_ac.GSTIN end),pos_std_cd =PT.GSTSCODE,pos = PT.gststate,Cons_pos =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.state else  Cons_ac.state end),seller_pos =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.state else  seller_ac.state  end),Cons_PANNO = Cons_ac.i_tax,seller_PANNO = seller_ac.i_tax,(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt,H.TRANSTATUS,gstype =(CASE WHEN ISNULL(D.ECredit,0) = 1 THEN (case when IT.Isservice = 0  then (case when IT.type = 'Machinery/Stores'
then 'Capital Goods' else 'Input Goods' end) else 'Input Services' end) else 'Ineligible for ITC' END),AVL_ITC = ISNULL(D.ECredit,0), '' as beno , '' as BEDT,d.gstrate,'' as portcode,'Debit Note for Purchases' as TransType,'' as TransSubType,Reason = '',Cons_shiptoId=(case WHEN isnull(H.scons_id, 0) > 0 then isnull(Cons_sp.shipto_id,0) else 0 end),Cons_LocId=Isnull(Cons_sp.Location_Id,''),ITC_Date=case when isnull(H.u_itcdate,'')>1900 then isnull(H.u_itcdate,'') else isnull(H.date,'') end,Cons_uid = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.UID,'') <> '' THEN Cons_sp.UID ELSE '' END ) else (CASE WHEN ISNULL(Cons_ac.UID,'') <> '' THEN Cons_ac.UID  ELSE '' END ) end) else (case WHEN isnull(H.sAc_id, 0) > 0 
then (CASE When isnull(seller_sp.UID,'') <> ''  then seller_sp.UID else '' end ) else  (CASE WHEN ISNULL(seller_ac.UID,'') <> '' THEN seller_ac.UID ELSE '' END) end) end),Supp_Desc = case when isnull(cast(it.it_desc as varchar(4000)),'')<>'' then cast(it.it_desc as varchar(4000)) else '' end,HSN_Desc = '',IsSerGoods = IT.Isservice,ItType = rtrim(ltrim(IT.Type)),iigst_amt=((ISNULL(D.igst_amt,0)+ ISNULL(D.IGSRT_AMT,0))-ISNULL(b.iigst_amt,0)),icgst_amt=((ISNULL(D.cgst_amt,0) + ISNULL(D.CGSRT_AMT,0)) - ISNULL(b.icgst_amt,0)),isGST_AMT=((isnull(D.sGST_AMT,0)+ isnull(D.SGSRT_AMT,0))-isnull(b.isGST_AMT,0)),ICESS_AMT = ((isnull(D.COMPCESS,0)+ isnull(D.COMRPCESS,0)) - isnull(B.ICESS_AMT,0))
,Gs_type = 'Goods','' as expotype,'Purchases' as OrgTransType,'' as OrgGstin FROM PRMAINAM H LEFT OUTER JOIN PRITEMAM D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) LEFT OUTER JOIN	IT_MAST IT ON (D .IT_CODE = IT.IT_CODE) LEFT OUTER JOIN	shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id ) LEFT OUTER JOIN	ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id) LEFT OUTER JOIN	shipto seller_sp ON (seller_sp.ac_id = h.Ac_id and seller_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN	ac_mast seller_ac ON (h.Ac_id = seller_ac.ac_id) INNER JOIN PRITREF REF ON (D.entry_ty = REF.entry_ty AND D.Tran_cd = REF.Tran_cd AND D.itserial =REF.Itserial)
INNER JOIN PTMAIN PT ON (REF.Itref_tran =PT.Tran_cd AND REF.rentry_ty=PT.entry_ty) left outer join epayment b on (D.Tran_cd = b.tran_cd and D.Entry_ty =b.entry_ty and d.ITSERIAL =b.itserial)
UNION ALL
/*Amendment details for Purchase Return*/
SELECT  H.Entry_ty, H.Tran_cd, D.ITSERIAL, H.INV_NO, H.Date,D.IT_CODE,D.QTY,isnull(d.u_asseamt,0) AS Taxableamt,isnull(d.CGST_PER,0) as CGST_PER,isnull(D.CGST_AMT,0) as CGST_AMT,isnull(d.SGST_PER,0) as SGST_PER,isnull(D.SGST_AMT,0)as SGST_AMT,isnull(d.IGST_PER,0) as IGST_PER,isnull(D.IGST_AMT,0) as IGST_AMT,d.sbillno as ORG_INVNO,d.sbdate as ORG_DATE,isnull(D.CGSRT_AMT,0) as CGSRT_AMT, isnull(D.SGSRT_AMT,0) as SGSRT_AMT,isnull(D.IGSRT_AMT,0) as IGSRT_AMT,isnull(D.GRO_AMT,0) as GRO_AMT,isnull(h.net_amt,0) as net_amt,D.CCESSRATE as Cess_per,isnull(D.COMPCESS,0) as Cess_amt,isnull(D.COMRPCESS,0) As CessRT_amt,D.LineRule,h.inv_sr,h.l_yn,IT.s_unit as uqc ,IT.IT_NAME,(CASE WHEN IT.Isservice = 0 THEN 'Goods' WHEN IT.Isservice = 1 THEN 'Services' ELSE '' END) AS Isservice, HSNCODE = (case when Isservice=0 then IT.HSNCODE else IT.ServTCode end),'' as RevCharge
,'' AS AGAINSTGS,AmendDate = (case when DATEDIFF(MM,H.DATE,H.AmendDAte) > 0 then h.AmendDate else ''  end ),Cons_ac_name =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else  Cons_ac.ac_name end),Cons_SUPP_TYPE =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.SUPP_TYPE else Cons_ac.SUPP_TYPE end ) else( case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end) end ),seller_SUPP_TYPE =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end),Cons_st_type =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.st_type else Cons_ac.st_type end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end) end),seller_st_type =(case WHEN isnull(H.sAc_id, 0) > 0 then  
seller_sp.st_type else  seller_ac.st_type end),Cons_gstin = (case when seller_ac.i_tax=Cons_ac.i_tax then	(case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.GSTIN,'') = '' THEN '' ELSE Cons_sp.GSTIN END ) else (CASE WHEN ISNULL(Cons_ac.GSTIN,'') = '' THEN '' ELSE Cons_ac.GSTIN  END )	end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(seller_sp.GSTIN,'') = ''  then '' else seller_sp.GSTIN end ) else (CASE WHEN ISNULL(seller_ac.GSTIN,'')= '' THEN '' ELSE seller_ac.GSTIN END) end) end),seller_gstin =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.GSTIN else  seller_ac.GSTIN end),pos_std_cd =PT.GSTSCODE,pos = PT.gststate ,Cons_pos =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.state else  Cons_ac.state end),seller_pos =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.state else  seller_ac.state  end),Cons_PANNO = Cons_ac.i_tax
,seller_PANNO = seller_ac.i_tax,(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt,H.TRANSTATUS,gstype =(CASE WHEN ISNULL(D.ECredit,0) = 1 THEN (case when IT.Isservice = 0  then (case when IT.type = 'Machinery/Stores' then 'Capital Goods' else 'Input Goods' end) else 'Input Services' end) else 'Ineligible for ITC' END),AVL_ITC = ISNULL(D.ECredit,0), '' as beno , '' as BEDT,d.gstrate,'' as portcode,'Debit Note for Purchases' as TransType,'' as TransSubType,Reason = '',Cons_shiptoId=(case WHEN isnull(H.scons_id, 0) > 0 then isnull(Cons_sp.shipto_id,0) else 0 end),Cons_LocId=Isnull(Cons_sp.Location_Id,''),ITC_Date=case when isnull(H.u_itcdate,'')>1900 then isnull(H.u_itcdate,'') else isnull(H.AmendDate,'') end,Cons_uid = (case when seller_ac.i_tax=Cons_ac.i_tax 
then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.UID,'') <> '' THEN Cons_sp.UID ELSE '' END ) else (CASE WHEN ISNULL(Cons_ac.UID,'') <> '' THEN Cons_ac.UID  ELSE '' END ) end) else (case WHEN isnull(H.sAc_id, 0) > 0 then (CASE When isnull(seller_sp.UID,'') <> ''  then seller_sp.UID else '' end ) else  (CASE WHEN ISNULL(seller_ac.UID,'') <> '' THEN seller_ac.UID ELSE '' END) end) end),Supp_Desc = case when isnull(cast(it.it_desc as varchar(4000)),'')<>'' then cast(it.it_desc as varchar(4000)) else '' end,HSN_Desc = '',IsSerGoods = IT.Isservice,ItType = rtrim(ltrim(IT.Type)),iigst_amt=((ISNULL(D.igst_amt,0)+ ISNULL(D.IGSRT_AMT,0))-ISNULL(b.iigst_amt,0)),icgst_amt=((ISNULL(D.cgst_amt,0) + ISNULL(D.CGSRT_AMT,0)) - ISNULL(b.icgst_amt,0)),isGST_AMT=((isnull(D.sGST_AMT,0)+ isnull(D.SGSRT_AMT,0))-isnull(b.isGST_AMT,0))
,ICESS_AMT = ((isnull(D.COMPCESS,0)+ isnull(D.COMRPCESS,0)) - isnull(B.ICESS_AMT,0)),Gs_type = 'Goods','' as expotype,'Debit Note for Purchases' as OrgTransType,H.Oldgstin as OrgGstin FROM PRMAIN H LEFT OUTER JOIN PRITEM D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) LEFT OUTER JOIN	IT_MAST IT ON (D .IT_CODE = IT.IT_CODE) LEFT OUTER JOIN	shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id ) LEFT OUTER JOIN	ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id) LEFT OUTER JOIN	shipto seller_sp ON (seller_sp.ac_id = h.Ac_id and seller_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN	ac_mast seller_ac ON (h.Ac_id = seller_ac.ac_id) INNER JOIN PRITREF REF ON (D.entry_ty = REF.entry_ty AND D.Tran_cd = REF.Tran_cd AND D.itserial =REF.Itserial) INNER JOIN PTMAIN PT ON (REF.Itref_tran =PT.Tran_cd AND REF.rentry_ty=PT.entry_ty)
left outer join epayment b on (D.Tran_cd = b.tran_cd  and D.Entry_ty =b.entry_ty and d.ITSERIAL =b.itserial) LEFT OUTER JOIN PRMAINAM AMD ON (H.entry_ty =AMD.ENTRY_TY AND H.Tran_cd =AMD.TRAN_CD ))AA
SELECT mCGST_PER = CAST(0 AS NUMERIC(7,2)),mSGST_PER = CAST(0 AS NUMERIC(7,2)),mIGST_PER = CAST(0 AS NUMERIC(7,2)),* INTO #INTEMP_2 FROM (
--Original details of Debit Note
SELECT H.Entry_ty, H.Tran_cd, D.ITSERIAL, H.INV_NO, H.DATE,D .IT_CODE,0.00 as QTY,isnull(d.u_asseamt,0) AS Taxableamt,isnull(d.CGST_PER,0) as CGST_PER,isnull(D.CGST_AMT,0)as CGST_AMT,isnull(d.SGST_PER,0) as SGST_PER,isnull(D.SGST_AMT,0) as SGST_AMT,isnull(d.IGST_PER,0) as IGST_PER,isnull(D.IGST_AMT,0) as IGST_AMT,d.sbillno as ORG_INVNO,d.sbdate as ORG_DATE,isnull(D.CGSRT_AMT,0) as CGSRT_AMT, isnull(D.SGSRT_AMT,0) as SGSRT_AMT,isnull(D.IGSRT_AMT,0) as IGSRT_AMT ,isnull(D.GRO_AMT,0) as GRO_AMT,isnull(h.net_amt,0) as net_amt ,D.CCESSRATE as Cess_per,isnull(D.COMPCESS,0) as Cess_amt,isnull(D.COMRPCESS,0) As CessRT_amt,D.LineRule,h.inv_sr,h.l_yn,IT.s_unit as uqc ,IT.IT_NAME,(CASE WHEN IT.Isservice = 0 THEN 'Goods' WHEN IT.Isservice = 1 THEN 'Services' ELSE '' END) AS Isservice, HSNCODE = (case when Isservice=0 then IT.HSNCODE else IT.ServTCode end),'' as RevCharge,H.AGAINSTGS,AmendDate = ''
,Cons_ac_name =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else  Cons_ac.ac_name end),Cons_SUPP_TYPE =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.SUPP_TYPE else Cons_ac.SUPP_TYPE end ) else( case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end) end ),seller_SUPP_TYPE =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end),Cons_st_type =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.st_type else Cons_ac.st_type end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else seller_ac.st_type end) end),seller_st_type =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end),Cons_gstin = (case when seller_ac.i_tax=Cons_ac.i_tax then	(case WHEN isnull(H.scons_id, 0) > 0
then (CASE WHEN ISNULL(Cons_sp.GSTIN,'') = '' THEN '' ELSE Cons_sp.GSTIN END ) else (CASE WHEN ISNULL(Cons_ac.GSTIN,'') = '' THEN '' ELSE Cons_ac.GSTIN  END ) end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(seller_sp.GSTIN,'') = ''  then '' else seller_sp.GSTIN end ) else  (CASE WHEN ISNULL(seller_ac.GSTIN,'')= '' THEN '' ELSE seller_ac.GSTIN END) end) end),seller_gstin =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.GSTIN  else  seller_ac.GSTIN  end),pos_std_cd =H.GSTSCODE,pos = H.GSTState ,Cons_pos =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.state else  Cons_ac.state end),seller_pos =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.state else  seller_ac.state  end),Cons_PANNO = Cons_ac.i_tax,seller_PANNO = seller_ac.i_tax,(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt,H.TRANSTATUS,gstype =(CASE WHEN ISNULL(D.ECredit,0) = 1 THEN (case when IT.Isservice = 0  then (case when IT.type = 'Machinery/Stores' then 'Capital Goods' else 'Input Goods' end) else 'Input Services' end) else 'Ineligible for ITC' END),AVL_ITC = ISNULL(D.ECredit,0), '' as beno , '' as BEDT ,d.gstrate ,'' as portcode,'Debit Note for Purchases' as TransType,'' as TransSubType,Reason = (case when isnull(H.u_gprice,'')<>'' then substring(H.u_gprice,charindex('-',H.u_gprice)+1,len(H.u_gprice)) else '' end),Cons_shiptoId=(case WHEN isnull(H.scons_id, 0) > 0 then isnull(Cons_sp.shipto_id,0) else 0 end),Cons_LocId=Isnull(Cons_sp.Location_Id,''),ITC_Date=case when isnull(H.u_itcdate,'')>1900 then isnull(H.u_itcdate,'') else isnull(H.date,'') end,Cons_uid = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.UID,'') <> '' THEN Cons_sp.UID ELSE '' END ) else (CASE WHEN ISNULL(Cons_ac.UID,'') <> '' THEN Cons_ac.UID  ELSE '' END ) end) else (case WHEN isnull(H.sAc_id, 0) > 0 then (CASE When isnull(seller_sp.UID,'') <> ''  then seller_sp.UID else '' end ) else  (CASE WHEN ISNULL(seller_ac.UID,'') <> '' THEN seller_ac.UID ELSE '' END) end) end),Supp_Desc = case when isnull(cast(it.it_desc as varchar(4000)),'')<>'' then cast(it.it_desc as varchar(4000)) else '' end,HSN_Desc = '',IsSerGoods = IT.Isservice,ItType = rtrim(ltrim(IT.Type)),iigst_amt=((ISNULL(D.igst_amt,0)+ ISNULL(D.IGSRT_AMT,0))-ISNULL(b.iigst_amt,0)),icgst_amt=((ISNULL(D.cgst_amt,0) + ISNULL(D.CGSRT_AMT,0)) - ISNULL(b.icgst_amt,0)),isGST_AMT=((isnull(D.sGST_AMT,0)+ isnull(D.SGSRT_AMT,0))-isnull(b.isGST_AMT,0)),ICESS_AMT = ((isnull(D.COMPCESS,0)+ isnull(D.COMRPCESS,0)) - isnull(B.ICESS_AMT,0))
,Gs_type = case when h.againstgs ='PURCHASES' then 'Goods' when h.againstgs = 'SERVICE PURCHASE BILL' then 'Services' END,'' as expotype,'Purchases' as OrgTransType,'' as OrgGstin FROM DNMAINAM H LEFT OUTER JOIN	DNITEMAM D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) LEFT OUTER JOIN	IT_MAST IT ON (D .IT_CODE = IT.IT_CODE) LEFT OUTER JOIN	shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id ) LEFT OUTER JOIN	ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id)
LEFT OUTER JOIN	shipto seller_sp ON (seller_sp.ac_id = h.Ac_id and seller_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN	ac_mast seller_ac ON (h.Ac_id = seller_ac.ac_id) left outer join epayment b on (D.Tran_cd = b.tran_cd  and D.Entry_ty =b.entry_ty and d.ITSERIAL =b.itserial) WHERE H.AGAINSTGS IN('PURCHASES','SERVICE PURCHASE BILL') AND H.entry_ty in ('GD','D6')
UNION ALL
/*Amendment details of Debit Note*/
SELECT  H.Entry_ty, H.Tran_cd, D.ITSERIAL, H.INV_NO, H.Date,D .IT_CODE,0.00 as QTY,isnull(d.u_asseamt,0) AS Taxableamt,isnull(d.CGST_PER,0) as CGST_PER,isnull(D.CGST_AMT,0)as CGST_AMT,isnull(d.SGST_PER,0) as SGST_PER,isnull(D.SGST_AMT,0) as SGST_AMT,isnull(d.IGST_PER,0) as IGST_PER,isnull(D.IGST_AMT,0) as IGST_AMT,d.sbillno as ORG_INVNO, d.sbdate as ORG_DATE,isnull(D.CGSRT_AMT,0) as CGSRT_AMT, isnull(D.SGSRT_AMT,0) as SGSRT_AMT,isnull(D.IGSRT_AMT,0) as IGSRT_AMT ,isnull(D.GRO_AMT,0) as GRO_AMT	,isnull(h.net_amt,0) as net_amt ,D.CCESSRATE as Cess_per
,isnull(D.COMPCESS,0) as Cess_amt,isnull(D.COMRPCESS,0) As CessRT_amt,D.LineRule,h.inv_sr,h.l_yn,IT.s_unit as uqc ,IT.IT_NAME,(CASE WHEN IT.Isservice = 0 THEN 'Goods' WHEN IT.Isservice = 1 THEN 'Services' ELSE '' END) AS Isservice, HSNCODE = (case when Isservice=0 then IT.HSNCODE else IT.ServTCode end),'' as RevCharge,H.AGAINSTGS,AmendDate = (case when DATEDIFF(MM,H.DATE,H.AmendDAte) > 0 then h.AmendDate else ''  end ),Cons_ac_name =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else  Cons_ac.ac_name end),Cons_SUPP_TYPE =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0
then  Cons_sp.SUPP_TYPE else Cons_ac.SUPP_TYPE end ) else( case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end) end ),seller_SUPP_TYPE =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end),Cons_st_type =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.st_type else  Cons_ac.st_type end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end) end),seller_st_type =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end)
,Cons_gstin = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.GSTIN,'') = '' THEN '' ELSE Cons_sp.GSTIN END ) else (CASE WHEN ISNULL(Cons_ac.GSTIN,'') = '' THEN '' ELSE Cons_ac.GSTIN  END ) end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(seller_sp.GSTIN,'') = ''  then '' else seller_sp.GSTIN end ) else  (CASE WHEN ISNULL(seller_ac.GSTIN,'')= '' THEN '' ELSE seller_ac.GSTIN END) end) end) ,seller_gstin =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.GSTIN  else  seller_ac.GSTIN  end),pos_std_cd =H.GSTSCODE
,pos = H.GSTState ,Cons_pos =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.state else  Cons_ac.state end),seller_pos =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.state else  seller_ac.state  end),Cons_PANNO = Cons_ac.i_tax ,seller_PANNO = seller_ac.i_tax,(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno ,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt,H.TRANSTATUS,gstype =(CASE WHEN ISNULL(D.ECredit,0) = 1 THEN (case when IT.Isservice = 0  then (case when IT.type = 'Machinery/Stores' then 'Capital Goods' else 'Input Goods' end) else 'Input Services' end) else 'Ineligible for ITC' END)
,AVL_ITC = ISNULL(D.ECredit,0), '' as beno , '' as BEDT ,d.gstrate ,'' as portcode,'Debit Note for Purchases' as TransType,'' as TransSubType,Reason = (case when isnull(H.u_gprice,'')<>'' then substring(H.u_gprice,charindex('-',H.u_gprice)+1,len(H.u_gprice)) else '' end),Cons_shiptoId=(case WHEN isnull(H.scons_id, 0) > 0 then isnull(Cons_sp.shipto_id,0) else 0 end),Cons_LocId=Isnull(Cons_sp.Location_Id,''),ITC_Date=case when isnull(H.u_itcdate,'')>1900 then isnull(H.u_itcdate,'') else isnull(H.AmendDate,'') end,Cons_uid = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.UID,'') <> '' THEN Cons_sp.UID ELSE '' END )
else (CASE WHEN ISNULL(Cons_ac.UID,'') <> '' THEN Cons_ac.UID  ELSE '' END ) end)else (case WHEN isnull(H.sAc_id, 0) > 0 then (CASE When isnull(seller_sp.UID,'') <> ''  then seller_sp.UID else '' end ) else  (CASE WHEN ISNULL(seller_ac.UID,'') <> '' THEN seller_ac.UID ELSE '' END) end) end),Supp_Desc = case when isnull(cast(it.it_desc as varchar(4000)),'')<>'' then cast(it.it_desc as varchar(4000)) else '' end,HSN_Desc = '',IsSerGoods = IT.Isservice,ItType = rtrim(ltrim(IT.Type)),iigst_amt=((ISNULL(D.igst_amt,0)+ ISNULL(D.IGSRT_AMT,0))-ISNULL(b.iigst_amt,0)),icgst_amt=((ISNULL(D.cgst_amt,0) + ISNULL(D.CGSRT_AMT,0)) - ISNULL(b.icgst_amt,0))
,isGST_AMT=((isnull(D.sGST_AMT,0)+ isnull(D.SGSRT_AMT,0))-isnull(b.isGST_AMT,0)),ICESS_AMT = ((isnull(D.COMPCESS,0)+ isnull(D.COMRPCESS,0)) - isnull(B.ICESS_AMT,0)),Gs_type = case when h.againstgs ='PURCHASES' then 'Goods' when h.againstgs = 'SERVICE PURCHASE BILL' then 'Services' END,'' as expotype
--,'Debit Note for Purchases' as OrgTransType  --Commented by Priyanka B on 13062019 for Bug-31816
,'Purchases' as OrgTransType  --Modified by Priyanka B on 13062019 for Bug-31816
,'' as OrgGstin FROM DNMAIN H LEFT OUTER JOIN DNITEM D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) LEFT OUTER JOIN	IT_MAST IT ON (D .IT_CODE = IT.IT_CODE) LEFT OUTER JOIN	shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id ) LEFT OUTER JOIN ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id)
LEFT OUTER JOIN	shipto seller_sp ON (seller_sp.ac_id = h.Ac_id and seller_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN	ac_mast seller_ac ON (h.Ac_id = seller_ac.ac_id) left outer join epayment b on (D.Tran_cd = b.tran_cd  and D.Entry_ty =b.entry_ty and d.ITSERIAL =b.itserial) LEFT OUTER JOIN DNMAINAM AMD ON (H.entry_ty =AMD.ENTRY_TY AND H.Tran_cd =AMD.TRAN_CD ) WHERE H.AGAINSTGS IN('PURCHASES','SERVICE PURCHASE BILL') AND H.entry_ty in ('GD','D6') 
UNION ALL
/*Original details of Credit Note*/
SELECT  H.Entry_ty, H.Tran_cd, D.ITSERIAL, H.INV_NO, H.DATE,D .IT_CODE,0.00 as QTY,isnull(d.u_asseamt,0) AS Taxableamt,isnull(d.CGST_PER,0) as CGST_PER,isnull(D.CGST_AMT,0) as CGST_AMT,isnull(d.SGST_PER,0) as SGST_PER,isnull(D.SGST_AMT,0) as SGST_AMT,isnull(d.IGST_PER,0) as IGST_PER,isnull(D.IGST_AMT,0) as IGST_AMT,d.sbillno as ORG_INVNO, d.sbdate as ORG_DATE,isnull(D.CGSRT_AMT,0) as CGSRT_AMT, isnull(D.SGSRT_AMT,0) as SGSRT_AMT,isnull(D.IGSRT_AMT,0) as IGSRT_AMT,isnull(D.GRO_AMT,0) as GRO_AMT,isnull(h.net_amt,0) as net_amt,D.CCESSRATE as Cess_per,isnull(D.COMPCESS,0) as Cess_amt,isnull(D.COMRPCESS,0) As CessRT_amt,D.LineRule,h.inv_sr,h.l_yn,IT.s_unit as uqc ,IT.IT_NAME
,(CASE WHEN IT.Isservice = 0 THEN 'Goods' WHEN IT.Isservice = 1 THEN 'Services' ELSE '' END) AS Isservice,HSNCODE = (case when Isservice=0 then IT.HSNCODE else IT.ServTCode end),RevCharge = '',H.AGAINSTGS,AmendDate = '',Cons_ac_name =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else  Cons_ac.ac_name end),Cons_SUPP_TYPE =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.SUPP_TYPE else Cons_ac.SUPP_TYPE end ) else( case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else seller_ac.SUPP_TYPE end) end ),seller_SUPP_TYPE =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end)
,Cons_st_type =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.st_type else  Cons_ac.st_type end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end) end),seller_st_type =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end),Cons_gstin = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.GSTIN,'') = '' THEN '' ELSE Cons_sp.GSTIN END ) else (CASE WHEN ISNULL(Cons_ac.GSTIN,'') = '' THEN '' ELSE Cons_ac.GSTIN  END ) end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(seller_sp.GSTIN,'') = ''  then ''
else seller_sp.GSTIN end ) else  (CASE WHEN ISNULL(seller_ac.GSTIN,'')= '' THEN '' ELSE seller_ac.GSTIN END)end) end),seller_gstin =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.GSTIN else  seller_ac.GSTIN  end),pos_std_cd =H.GSTSCODE,pos = H.GSTState ,Cons_pos =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.state else  Cons_ac.state end),seller_pos =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.state else  seller_ac.state  end),Cons_PANNO = Cons_ac.i_tax,seller_PANNO = seller_ac.i_tax ,(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt,H.TRANSTATUS,gstype =(CASE WHEN ISNULL(D.ECredit,0) = 1 THEN (case when IT.Isservice = 0  then (case when IT.type = 'Machinery/Stores'
then 'Capital Goods' else 'Input Goods' end) else 'Input Services' end) else 'Ineligible for ITC' END),AVL_ITC = ISNULL(D.ECredit,0), '' as beno , '' as BEDT ,d.gstrate ,'' as portcode,'Credit Note for Purchases' as TransType,'' as TransSubType,Reason = (case when isnull(H.u_gprice,'')<>'' then substring(H.u_gprice,charindex('-',H.u_gprice)+1,len(H.u_gprice)) else '' end),Cons_shiptoId=(case WHEN isnull(H.scons_id, 0) > 0 then isnull(Cons_sp.shipto_id,0) else 0 end),Cons_LocId=Isnull(Cons_sp.Location_Id,''),ITC_Date=case when isnull(H.u_itcdate,'')>1900 then isnull(H.u_itcdate,'') else isnull(H.date,'') end,Cons_uid = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.UID,'') <> '' THEN Cons_sp.UID ELSE '' END )
else (CASE WHEN ISNULL(Cons_ac.UID,'') <> '' THEN Cons_ac.UID  ELSE '' END ) end) else (case WHEN isnull(H.sAc_id, 0) > 0 then (CASE When isnull(seller_sp.UID,'') <> ''  then seller_sp.UID else '' end ) else  (CASE WHEN ISNULL(seller_ac.UID,'') <> '' THEN seller_ac.UID ELSE '' END) end) end),Supp_Desc = case when isnull(cast(it.it_desc as varchar(4000)),'')<>'' then cast(it.it_desc as varchar(4000)) else '' end,HSN_Desc = '',IsSerGoods = IT.Isservice,ItType = rtrim(ltrim(IT.Type)),iigst_amt=((ISNULL(D.igst_amt,0)+ ISNULL(D.IGSRT_AMT,0))-ISNULL(b.iigst_amt,0)),icgst_amt=((ISNULL(D.cgst_amt,0) + ISNULL(D.CGSRT_AMT,0)) - ISNULL(b.icgst_amt,0)),isGST_AMT=((isnull(D.sGST_AMT,0)+ isnull(D.SGSRT_AMT,0))-isnull(b.isGST_AMT,0)),ICESS_AMT = ((isnull(D.COMPCESS,0)+ isnull(D.COMRPCESS,0)) - isnull(B.ICESS_AMT,0))
,Gs_type = case when h.againstgs ='PURCHASES' then 'Goods' when h.againstgs = 'SERVICE PURCHASE BILL' then 'Services' END,'' as expotype,'Purchases' as OrgTransType,'' as OrgGstin FROM CNMAINAM H left outer JOIN CNITEMAM D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) left outer JOIN IT_MAST IT ON (D .IT_CODE = IT.IT_CODE) LEFT OUTER JOIN shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id ) LEFT OUTER JOIN ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id) LEFT OUTER JOIN shipto seller_sp ON (seller_sp.ac_id = h.Ac_id and seller_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN ac_mast seller_ac ON (h.Ac_id = seller_ac.ac_id) left outer join epayment b on (D.Tran_cd = b.tran_cd  and D.Entry_ty =b.entry_ty and d.ITSERIAL =b.itserial) WHERE H.AGAINSTGS IN('PURCHASES','SERVICE PURCHASE BILL')
AND H.entry_ty in ('GC','C6')
UNION ALL
/*Amendment details of Credit Note*/
SELECT  H.Entry_ty, H.Tran_cd, D.ITSERIAL, H.INV_NO, H.Date,D .IT_CODE,0.00 as QTY,isnull(d.u_asseamt,0) AS Taxableamt,isnull(d.CGST_PER,0) as CGST_PER,isnull(D.CGST_AMT,0) as CGST_AMT,isnull(d.SGST_PER,0) as SGST_PER,isnull(D.SGST_AMT,0) as SGST_AMT,isnull(d.IGST_PER,0) as IGST_PER,isnull(D.IGST_AMT,0) as IGST_AMT,d.sbillno as ORG_INVNO, d.sbdate as ORG_DATE,isnull(D.CGSRT_AMT,0) as CGSRT_AMT, isnull(D.SGSRT_AMT,0) as SGSRT_AMT,isnull(D.IGSRT_AMT,0) as IGSRT_AMT ,isnull(D.GRO_AMT,0) as GRO_AMT,isnull(h.net_amt,0) as net_amt,D.CCESSRATE as Cess_per,isnull(D.COMPCESS,0) as Cess_amt,isnull(D.COMRPCESS,0) As CessRT_amt,D.LineRule,h.inv_sr,h.l_yn,IT.s_unit as uqc ,IT.IT_NAME,(CASE WHEN IT.Isservice = 0 THEN 'Goods' WHEN IT.Isservice = 1 THEN 'Services' ELSE '' END) AS Isservice
, HSNCODE = (case when Isservice=0 then IT.HSNCODE else IT.ServTCode end),'' as RevCharge,H.AGAINSTGS,AmendDate = (case when DATEDIFF(MM,H.DATE,H.AmendDAte) > 0 then h.AmendDate else ''  end ),Cons_ac_name =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else  Cons_ac.ac_name end),Cons_SUPP_TYPE =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.SUPP_TYPE else Cons_ac.SUPP_TYPE end ) else( case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end) end ),seller_SUPP_TYPE =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end),Cons_st_type =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.st_type else Cons_ac.st_type end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type
else  seller_ac.st_type end) end),seller_st_type =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end),Cons_gstin = (case when seller_ac.i_tax=Cons_ac.i_tax then	(case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.GSTIN,'') = '' THEN '' ELSE Cons_sp.GSTIN END ) else (CASE WHEN ISNULL(Cons_ac.GSTIN,'') = '' THEN '' ELSE Cons_ac.GSTIN  END )	end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(seller_sp.GSTIN,'') = ''  then '' else seller_sp.GSTIN end ) else  (CASE WHEN ISNULL(seller_ac.GSTIN,'')= '' THEN '' ELSE seller_ac.GSTIN END) end) end),seller_gstin =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.GSTIN else  seller_ac.GSTIN  end),pos_std_cd =H.GSTSCODE,pos = H.GSTState ,Cons_pos =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.state else  Cons_ac.state end)
,seller_pos =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.state else  seller_ac.state  end),Cons_PANNO = Cons_ac.i_tax,seller_PANNO = seller_ac.i_tax,(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt,H.TRANSTATUS,gstype =(CASE WHEN ISNULL(D.ECredit,0) = 1 THEN (case when IT.Isservice = 0  then (case when IT.type = 'Machinery/Stores' then 'Capital Goods' else 'Input Goods' end) else 'Input Services' end) else 'Ineligible for ITC' END),AVL_ITC = ISNULL(D.ECredit,0), '' as beno , '' as BEDT ,d.gstrate ,'' as portcode,'Credit Note for Purchases' as TransType,'' as TransSubType,Reason = (case when isnull(H.u_gprice,'')<>'' then substring(H.u_gprice,charindex('-',H.u_gprice)+1,len(H.u_gprice)) else '' end),Cons_shiptoId=(case WHEN isnull(H.scons_id, 0) > 0 then isnull(Cons_sp.shipto_id,0) else 0 end)
,Cons_LocId=Isnull(Cons_sp.Location_Id,''),ITC_Date=case when isnull(H.u_itcdate,'')>1900 then isnull(H.u_itcdate,'') else isnull(H.AmendDate,'') end,Cons_uid = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.UID,'') <> '' THEN Cons_sp.UID ELSE '' END ) else (CASE WHEN ISNULL(Cons_ac.UID,'') <> '' THEN Cons_ac.UID  ELSE '' END ) end) else (case WHEN isnull(H.sAc_id, 0) > 0 then (CASE When isnull(seller_sp.UID,'') <> ''  then seller_sp.UID else '' end ) else  (CASE WHEN ISNULL(seller_ac.UID,'') <> '' THEN seller_ac.UID ELSE '' END) end) end),Supp_Desc = case when isnull(cast(it.it_desc as varchar(4000)),'')<>'' then cast(it.it_desc as varchar(4000)) else '' end,HSN_Desc = '',IsSerGoods = IT.Isservice,ItType = rtrim(ltrim(IT.Type)),iigst_amt=((ISNULL(D.igst_amt,0)+ ISNULL(D.IGSRT_AMT,0))-ISNULL(b.iigst_amt,0))
,icgst_amt=((ISNULL(D.cgst_amt,0) + ISNULL(D.CGSRT_AMT,0)) - ISNULL(b.icgst_amt,0)),isGST_AMT=((isnull(D.sGST_AMT,0)+ isnull(D.SGSRT_AMT,0))-isnull(b.isGST_AMT,0)),ICESS_AMT = ((isnull(D.COMPCESS,0)+ isnull(D.COMRPCESS,0)) - isnull(B.ICESS_AMT,0)),Gs_type = case when h.againstgs ='PURCHASES' then 'Goods' when h.againstgs = 'SERVICE PURCHASE BILL' then 'Services' END,'' as expotype
--,'Credit Note for Purchases' as OrgTransType  --Commented by Priyanka B on 13062019 for Bug-31816
,'Purchases' as OrgTransType  --Modified by Priyanka B on 13062019 for Bug-31816
,'' as OrgGstin FROM CNMAIN H left outer JOIN	CNITEM D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) left outer JOIN IT_MAST IT ON (D .IT_CODE = IT.IT_CODE) LEFT OUTER JOIN	shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id ) LEFT OUTER JOIN	ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id) LEFT OUTER JOIN	shipto seller_sp ON (seller_sp.ac_id = h.Ac_id and seller_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN	ac_mast seller_ac ON (h.Ac_id = seller_ac.ac_id)
left outer join epayment b on (D.Tran_cd = b.tran_cd  and D.Entry_ty =b.entry_ty and d.ITSERIAL =b.itserial) LEFT OUTER JOIN CNMAINAM AMD ON (H.entry_ty =AMD.ENTRY_TY AND H.Tran_cd =AMD.TRAN_CD ) WHERE H.AGAINSTGS IN('PURCHASES','SERVICE PURCHASE BILL') AND H.entry_ty in ('GC','C6') 
UNION ALL
--Original Details of Service Purchase Bill
SELECT  H.Entry_ty, H.Tran_cd, D.ITSERIAL, H.INV_NO, H.DATE,D .IT_CODE,D.QTY,isnull(d.u_asseamt,0) AS Taxableamt,isnull(d.CGST_PER,0) as CGST_PER,isnull(D.CGST_AMT,0) as CGST_AMT,isnull(d.SGST_PER,0) as SGST_PER,isnull(D.SGST_AMT,0) as SGST_AMT,isnull(d.IGST_PER,0) as IGST_PER,isnull(D.IGST_AMT,0) as IGST_AMT,ORG_INVNO='', ORG_DATE='',isnull(D.CGSRT_AMT,0) as CGSRT_AMT, isnull(D.SGSRT_AMT,0) as SGSRT_AMT,isnull(D.IGSRT_AMT,0)as IGSRT_AMT,isnull(D.GRO_AMT,0) as GRO_AMT,isnull(h.net_amt,0) as net_amt,'' as Cess_per,0.00 as Cess_amt,0.00 As CessRT_amt,D.LineRule,h.inv_sr,h.l_yn,IT.s_unit as uqc ,IT.IT_NAME,(CASE WHEN IT.Isservice = 0 THEN 'Goods' WHEN IT.Isservice = 1 THEN 'Services' ELSE '' END) AS Isservice, HSNCODE = (case when Isservice=0 then IT.HSNCODE else IT.ServTCode end),'' as RevCharge,'' AS AGAINSTGS,AmendDate = (case when DATEDIFF(MM,H.DATE,H.AmendDAte) > 0 then h.AmendDate else ''  end )
,Cons_ac_name =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else  Cons_ac.ac_name end),Cons_SUPP_TYPE =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.SUPP_TYPE else Cons_ac.SUPP_TYPE end ) else( case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end) end ),seller_SUPP_TYPE =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end),Cons_st_type =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.st_type else  Cons_ac.st_type end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end) end),seller_st_type =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end),Cons_gstin = (case when seller_ac.i_tax=Cons_ac.i_tax then	(case WHEN isnull(H.scons_id, 0) > 0
then (CASE WHEN ISNULL(Cons_sp.GSTIN,'') = '' THEN '' ELSE Cons_sp.GSTIN END ) else (CASE WHEN ISNULL(Cons_ac.GSTIN,'') = '' THEN '' ELSE Cons_ac.GSTIN  END )	end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(seller_sp.GSTIN,'') = ''  then '' else seller_sp.GSTIN end ) else  (CASE WHEN ISNULL(seller_ac.GSTIN,'')= '' THEN '' ELSE seller_ac.GSTIN END) end) end),seller_gstin =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.GSTIN  else  seller_ac.GSTIN end),pos_std_cd =H.GSTSCODE,pos = H.GSTState ,Cons_pos =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.state else  Cons_ac.state end),seller_pos =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.state else  seller_ac.state  end),Cons_PANNO = Cons_ac.i_tax,seller_PANNO = seller_ac.i_tax,(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt,H.TRANSTATUS
,gstype =(CASE WHEN ISNULL(D.ECredit,0) = 1 THEN (case when IT.Isservice = 0  then (case when IT.type = 'Machinery/Stores' then 'Capital Goods' else 'Input Goods' end) else 'Input Services' end) else 'Ineligible for ITC' END),AVL_ITC = ISNULL(D.ECredit,0), '' as beno , '' as BEDT ,d.gstrate ,'' as portcode,'Purchases' as TransType,H.U_IMPORM as TransSubType,Reason = '',Cons_shiptoId=(case WHEN isnull(H.scons_id, 0) > 0 then isnull(Cons_sp.shipto_id,0) else 0 end),Cons_LocId=Isnull(Cons_sp.Location_Id,''),ITC_Date=case when isnull(H.u_itcdate,'')>1900 then isnull(H.u_itcdate,'') else isnull(H.date,'') end,Cons_uid = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.UID,'') <> '' THEN Cons_sp.UID ELSE '' END ) else (CASE WHEN ISNULL(Cons_ac.UID,'') <> '' THEN Cons_ac.UID  ELSE '' END ) end) else (case WHEN isnull(H.sAc_id, 0) > 0 then (CASE When isnull(seller_sp.UID,'') <> ''
then seller_sp.UID else '' end ) else  (CASE WHEN ISNULL(seller_ac.UID,'') <> '' THEN seller_ac.UID ELSE '' END) end) end),Supp_Desc = case when isnull(cast(it.it_desc as varchar(4000)),'')<>'' then cast(it.it_desc as varchar(4000)) else '' end,HSN_Desc = '',IsSerGoods = IT.Isservice,ItType = rtrim(ltrim(IT.Type)),iigst_amt=((ISNULL(D.igst_amt,0)+ ISNULL(D.IGSRT_AMT,0))-ISNULL(b.iigst_amt,0)),icgst_amt=((ISNULL(D.cgst_amt,0) + ISNULL(D.CGSRT_AMT,0)) - ISNULL(b.icgst_amt,0)),isGST_AMT=((isnull(D.sGST_AMT,0)+ isnull(D.SGSRT_AMT,0))-isnull(b.isGST_AMT,0)),ICESS_AMT = ((isnull(D.COMPCESS,0)+ isnull(D.COMRPCESS,0)) - isnull(B.ICESS_AMT,0)),Gs_type = 'Services',h.expotype,'' as OrgTransType,'' as OrgGstin FROM EPMAINAM H LEFT OUTER JOIN	EPITEMAM D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) LEFT OUTER JOIN	IT_MAST IT ON (D .IT_CODE = IT.IT_CODE) LEFT OUTER JOIN	shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id )
LEFT OUTER JOIN	ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id) LEFT OUTER JOIN	shipto seller_sp ON (seller_sp.ac_id = h.Ac_id and seller_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN	ac_mast seller_ac ON (h.Ac_id = seller_ac.ac_id) left outer join epayment b on (D.Tran_cd = b.tran_cd  and D.Entry_ty =b.entry_ty and d.ITSERIAL =b.itserial) Where H.entry_ty in ('E1') AND (Cons_ac.supp_type<>'Unregistered' or Seller_ac.supp_type<>'Unregistered')
UNION ALL
/*Amendment details of Service Purchase Bill*/
SELECT  H.Entry_ty, H.Tran_cd, D.ITSERIAL, H.INV_NO, H.Date,D .IT_CODE,D.QTY,isnull(d.u_asseamt,0)  AS Taxableamt,isnull(d.CGST_PER,0) as CGST_PER,isnull(D.CGST_AMT,0) as CGST_AMT,isnull(d.SGST_PER,0) as SGST_PER,isnull(D.SGST_AMT,0) as SGST_AMT,isnull(d.IGST_PER,0) as IGST_PER,isnull(D.IGST_AMT,0) as IGST_AMT
--,ORG_INVNO=H.pinvno,ORG_DATE=H.pinvdt   --Commented by Priyanka B on 15012018 for Bug-30832
,ORG_INVNO=(case when isnull(H.amenddate,'')<>'' then amd.pinvno else '' end),ORG_DATE=(case when isnull(H.amenddate,'')<>'' then amd.pinvdt else '' end)   --Modified by Priyanka B on 15012018 for Bug-30832
,isnull(D.CGSRT_AMT,0) as CGSRT_AMT, isnull(D.SGSRT_AMT,0) as SGSRT_AMT,isnull(D.IGSRT_AMT,0)as IGSRT_AMT,isnull(D.GRO_AMT,0) as GRO_AMT,isnull(h.net_amt,0) as net_amt,'' as Cess_per,0.00 as Cess_amt,0.00 As CessRT_amt,D.LineRule,h.inv_sr,h.l_yn,IT.s_unit as uqc ,IT.IT_NAME,(CASE WHEN IT.Isservice = 0 THEN 'Goods' WHEN IT.Isservice = 1 THEN 'Services' ELSE '' END) AS Isservice,HSNCODE = (case when Isservice=0 then IT.HSNCODE else IT.ServTCode end),'' as RevCharge,'' AS AGAINSTGS,AmendDate = (case when DATEDIFF(MM,H.DATE,H.AmendDAte) > 0 then h.AmendDate else ''  end ),Cons_ac_name =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else  Cons_ac.ac_name end),Cons_SUPP_TYPE =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.SUPP_TYPE else Cons_ac.SUPP_TYPE end ) else( case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end) end ),seller_SUPP_TYPE =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.SUPP_TYPE else  seller_ac.SUPP_TYPE end),Cons_st_type =(case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.st_type else  Cons_ac.st_type end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end) end),seller_st_type =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.st_type else  seller_ac.st_type end),Cons_gstin = (case when seller_ac.i_tax=Cons_ac.i_tax then	(case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.GSTIN,'') = '' THEN '' ELSE Cons_sp.GSTIN END ) else (CASE WHEN ISNULL(Cons_ac.GSTIN,'') = '' THEN '' ELSE Cons_ac.GSTIN  END )	end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(seller_sp.GSTIN,'') = ''  then '' else seller_sp.GSTIN end ) else  (CASE WHEN ISNULL(seller_ac.GSTIN,'')= '' THEN '' ELSE seller_ac.GSTIN END) end) end),seller_gstin =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.GSTIN  else  seller_ac.GSTIN end)
,pos_std_cd=H.GSTSCODE,pos = H.GSTState ,Cons_pos =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.state else Cons_ac.state end),seller_pos =(case WHEN isnull(H.sAc_id, 0) > 0 then  seller_sp.state else  seller_ac.state end),Cons_PANNO = Cons_ac.i_tax,seller_PANNO = seller_ac.i_tax,(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt,H.TRANSTATUS,gstype =(CASE WHEN ISNULL(D.ECredit,0) = 1 THEN (case when IT.Isservice = 0  then (case when IT.type = 'Machinery/Stores' then 'Capital Goods' else 'Input Goods' end) else 'Input Services' end) else 'Ineligible for ITC' END),AVL_ITC = ISNULL(D.ECredit,0), '' as beno , '' as BEDT ,d.gstrate ,'' as portcode,'Purchases' as TransType,H.U_IMPORM as TransSubType,Reason = ''
,Cons_shiptoId=(case WHEN isnull(H.scons_id, 0) > 0 then isnull(Cons_sp.shipto_id,0) else 0 end),Cons_LocId=Isnull(Cons_sp.Location_Id,''),ITC_Date=case when isnull(H.u_itcdate,'')>1900 then isnull(H.u_itcdate,'') else isnull(H.AmendDate,'') end,Cons_uid = (case when seller_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.UID,'') <> '' THEN Cons_sp.UID ELSE '' END ) else (CASE WHEN ISNULL(Cons_ac.UID,'') <> '' THEN Cons_ac.UID  ELSE '' END ) end)else (case WHEN isnull(H.sAc_id, 0) > 0 then (CASE When isnull(seller_sp.UID,'') <> '' then seller_sp.UID else '' end ) else  (CASE WHEN ISNULL(seller_ac.UID,'') <> '' THEN seller_ac.UID ELSE '' END) end) end),Supp_Desc = case when isnull(cast(it.it_desc as varchar(4000)),'')<>'' then cast(it.it_desc as varchar(4000)) else '' end,HSN_Desc = '',IsSerGoods = IT.Isservice,ItType = rtrim(ltrim(IT.Type)),iigst_amt=((ISNULL(D.igst_amt,0)+ ISNULL(D.IGSRT_AMT,0))-ISNULL(b.iigst_amt,0)),icgst_amt=((ISNULL(D.cgst_amt,0) + ISNULL(D.CGSRT_AMT,0)) - ISNULL(b.icgst_amt,0)),isGST_AMT=((isnull(D.sGST_AMT,0)+ isnull(D.SGSRT_AMT,0))-isnull(b.isGST_AMT,0)),ICESS_AMT = ((isnull(D.COMPCESS,0)+ isnull(D.COMRPCESS,0)) - isnull(B.ICESS_AMT,0)),Gs_type = 'Services',h.expotype
--,'Purchases' as OrgTransType  --Commented by Priyanka B on 15012018 for Bug-30832
,(case when isnull(H.amenddate,'')<>'' then 'Purchases' else '' end) as OrgTransType  --Modified by Priyanka B on 15012018 for Bug-30832
,H.Oldgstin as OrgGstin FROM EPMAIN H LEFT OUTER JOIN	EPITEM D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) LEFT OUTER JOIN IT_MAST IT ON (D .IT_CODE = IT.IT_CODE) LEFT OUTER JOIN	shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id ) LEFT OUTER JOIN	ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id) LEFT OUTER JOIN	shipto seller_sp ON (seller_sp.ac_id = h.Ac_id and seller_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN	ac_mast seller_ac ON (h.Ac_id = seller_ac.ac_id) left outer join epayment b on (D.Tran_cd = b.tran_cd  and D.Entry_ty =b.entry_ty and d.ITSERIAL =b.itserial) LEFT OUTER JOIN EPMAINAM AMD ON (H.entry_ty =AMD.ENTRY_TY AND H.Tran_cd =AMD.TRAN_CD ) Where H.entry_ty in ('E1') AND (Cons_ac.supp_type<>'Unregistered' or
Seller_ac.supp_type<>'Unregistered'))BB

SELECT * INTO #INTEMP_3 
FROM (
		SELECT * FROM #INTEMP_1 
		UNION ALL 
		SELECT * FROM #INTEMP_2
	)CC 
WHERE ((case when ISNULL(AmendDAte,'') <> '' then AmendDate else DATE  end ) BETWEEN @LStartDate AND @LEndDate) 
ORDER BY DATE,INV_NO

UPDATE A SET mCGST_PER = (CASE WHEN ISNULL(GSTRATE,0) > 0  AND (ISNULL(CGSRT_AMT,0) + ISNULL(CGST_AMT,0)) > 0 AND ISNULL(CGST_PER,0) = 0 
					THEN GSTRATE/2 ELSE CGST_PER END) 
			,mSGST_PER = (CASE WHEN ISNULL(GSTRATE,0) > 0  AND (ISNULL(SGSRT_AMT,0) + ISNULL(SGST_AMT,0)) > 0 AND ISNULL(SGST_PER,0) = 0 
					THEN GSTRATE/2 ELSE SGST_PER END)
			,mIGST_PER = (CASE WHEN ISNULL(GSTRATE,0) > 0  AND (ISNULL(IGSRT_AMT,0) + ISNULL(IGST_AMT,0)) > 0 AND ISNULL(IGST_PER,0) = 0 
					THEN GSTRATE ELSE IGST_PER END) 
		FROM #INTEMP_3 A

SELECT * FROM #INTEMP_3 

DROP TABLE #SELF 
DROP TABLE #INTEMP_1  
DROP TABLE #INTEMP_2 
DROP TABLE #INTEMP_3
