IF EXISTS(SELECT * FROM SYSOBJECTS WHERE XTYPE='P' AND [NAME]='USP_EXTRACTION_INWARD_BANKCASH_EXCEL_FILE')
BEGIN
	DROP PROCEDURE USP_EXTRACTION_INWARD_BANKCASH_EXCEL_FILE
END

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- AUTHOR	  :	PRIYANKA B.
-- CREATE DATE: 07/03/2018
-- DESCRIPTION:	THIS STORED PROCEDURE IS USEFUL TO GENERATE INWARD BANK & CASH EXCEL EXTRACTION FILE.
-- MODIFIED BY: 
-- MODIFY DATE: 
-- REMARK:
-- =============================================
--set dateformat dmy execute USP_EXTRACTION_INWARD_BANKCASH_EXCEL_FILE '01/01/2017','31/01/2018'

CREATE PROCEDURE  [dbo].[USP_EXTRACTION_INWARD_BANKCASH_EXCEL_FILE]
@LSTARTDATE  SMALLDATETIME,@LENDDATE SMALLDATETIME
AS

SET DATEFORMAT dmy	
SELECT mCGST_PER=CAST(0 AS NUMERIC(7,2)),mSGST_PER=CAST(0 AS NUMERIC(7,2)),mIGST_PER=CAST(0 AS NUMERIC(7,2)),* INTO #BANKCASH FROM (SELECT  H.Entry_ty, H.Tran_cd, D.ITSERIAL, H.INV_NO, H.DATE,D .IT_CODE,D.QTY,isnull(d.u_asseamt,0) AS Taxableamt,isnull(d.CGST_PER,0) as CGST_PER,isnull(D.CGST_AMT,0) as CGST_AMT,isnull(d.SGST_PER,0)as SGST_PER,isnull(D.SGST_AMT,0) as SGST_AMT,isnull(d.IGST_PER,0) as IGST_PER,isnull(D.IGST_AMT,0) as IGST_AMT,ORG_INVNO=SPACE(50), cast('' as datetime ) as ORG_DATE
,isnull(D.CGSRT_AMT,0) as CGSRT_AMT, isnull(D.SGSRT_AMT,0)as SGSRT_AMT,isnull(D.IGSRT_AMT,0) as IGSRT_AMT,isnull(D.GRO_AMT,0) as GRO_AMT,isnull(h.net_amt,0) as net_amt,'' as Cess_per,isnull(d.COMPCESS,0) as Cess_amt,isnull(d.COMRPCESS,0) As CessRT_amt,D.LineRule,h.inv_sr,h.l_yn,IT.s_unit as uqc ,IT.IT_NAME,(CASE WHEN IT.Isservice = 0 THEN 'Goods' WHEN IT.Isservice = 1 THEN 'Services' ELSE '' END) AS Isservice, HSNCODE = (case when Isservice=0 then IT.HSNCODE else IT.ServTCode end)
,RevCharge = '',h.AGAINSTGS,AmendDate='' ,Cons_ac_name =(case WHEN isnull(h.sAc_id, 0) > 0 then  buyer_sp.mailname else  ac.ac_name end) ,Cons_SUPP_TYPE =(case WHEN isnull(h.sAc_id, 0) > 0 then  buyer_sp.Supp_type else  ac.Supp_type  end) ,buyer_SUPP_TYPE =(case WHEN isnull(h.sAc_id, 0) > 0 then  buyer_sp.SUPP_TYPE else  ac.SUPP_TYPE end) ,Cons_st_type =(case WHEN isnull(h.sAc_id, 0) > 0 then  buyer_sp.st_type else  ac.st_type end) ,buyer_st_type =(case WHEN isnull(h.sAc_id, 0) > 0 then  buyer_sp.st_type else  ac.st_type end)
,Cons_gstin =(case WHEN isnull(h.sAc_id, 0) > 0 then buyer_sp.GSTIN  else  ac.GSTIN  end) ,buyer_gstin =(case WHEN isnull(h.sAc_id, 0) > 0 then buyer_sp.GSTIN else  ac.GSTIN end) ,pos_std_cd =h.GSTSCODE,pos = h.gststate ,Cons_pos =buyer_sp.state ,buyer_pos =buyer_sp.state ,Cons_PANNO = ac.i_tax,buyer_PANNO = ac.i_tax ,(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno ,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt,0 as TRANSTATUS ,gstype ='' ,AVL_ITC = 0, '' as beno , '' as BEDT ,d.gstrate
,'' as portcode,PaymentType ='Advance payment',lcode.Code_nm as TransType,'' as TransSubType,Reason = '',Cons_shiptoId=isnull(buyer_sp.shipto_id,0),Cons_LocId=Isnull(buyer_sp.Location_Id,'')
--,ITC_Date=case when isnull(H.u_cldt,'')>1900 then isnull(H.u_cldt,'') else isnull(H.date,'') end
FROM BPMAIN H left outer JOIN BPITEM D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) left outer JOIN IT_MAST IT ON (D .IT_CODE = IT.IT_CODE) LEFT OUTER JOIN shipto buyer_sp ON (buyer_sp.ac_id = h.Ac_id and buyer_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN ac_mast ac ON (h.Ac_id  = ac.ac_id) LEFT OUTER JOIN lcode  ON (lcode.Entry_ty = h.Entry_ty) WHERE H.TDSPAYTYPE = 2 AND H.ENTRY_TY ='BP' AND (D.SGSRT_AMT + D.CGSRT_AMT + D.IGSRT_AMT + D.COMRPCESS ) > 0 AND (H.DATE BETWEEN @LStartDate AND @LEndDate)
Union all SELECT  H.Entry_ty, H.Tran_cd, D.ITSERIAL, H.INV_NO, H.DATE,D .IT_CODE,D.QTY,isnull(d.u_asseamt,0) AS Taxableamt,isnull(d.CGST_PER,0) as CGST_PER,isnull(D.CGST_AMT,0) as CGST_AMT,isnull(d.SGST_PER,0) as SGST_PER,isnull(D.SGST_AMT,0)as SGST_AMT ,isnull(d.IGST_PER,0) as IGST_PER,isnull(D.IGST_AMT,0)as IGST_AMT,ORG_INVNO=SPACE(50), cast('' as datetime ) as ORG_DATE,isnull(D.CGSRT_AMT,0) as CGSRT_AMT, isnull(D.SGSRT_AMT,0)as SGSRT_AMT ,isnull(D.IGSRT_AMT,0) as IGSRT_AMT ,isnull(D.GRO_AMT,0) as GRO_AMT
,isnull(h.net_amt,0) as net_amt,'' as Cess_per,isnull(d.COMPCESS,0) as Cess_amt,isnull(d.COMRPCESS,0) As CessRT_amt,D.LineRule,h.inv_sr,h.l_yn,IT.s_unit as uqc ,IT.IT_NAME,(CASE WHEN IT.Isservice = 0 THEN 'Goods' WHEN IT.Isservice = 1 THEN 'Services' ELSE '' END) AS Isservice, HSNCODE = (case when Isservice=0 then IT.HSNCODE else IT.ServTCode end),RevCharge = '',h.AGAINSTGS,AmendDate='',Cons_ac_name =Cons_ac.ac_name,Cons_SUPP_TYPE =Cons_ac.SUPP_TYPE,buyer_SUPP_TYPE =Cons_ac.SUPP_TYPE,Cons_st_type =Cons_ac.st_type
,buyer_st_type =Cons_ac.st_type,Cons_gstin =(CASE WHEN ISNULL(Cons_ac.GSTIN,'')='' THEN Cons_ac.UID ELSE Cons_ac.GSTIN END),buyer_gstin =(CASE WHEN ISNULL(Cons_ac.GSTIN,'')='' THEN Cons_ac.UID ELSE Cons_ac.GSTIN END),pos_std_cd =h.GSTSCODE,pos = h.gststate,Cons_pos =Cons_ac.state,buyer_pos =Cons_ac.state,Cons_PANNO = Cons_ac.i_tax,buyer_PANNO = Cons_ac.i_tax,(case when h.pinvno <> ''  then  h.pinvno else H.INV_NO end) as pinvno ,(case when h.pinvdt <> ''  then  h.pinvdt else H.date end) as pinvdt, 0 as TRANSTATUS,gstype = ''
,AVL_ITC = 0, '' as beno , '' as BEDT ,d.gstrate ,'' as portcode,PaymentType ='Advance payment',lcode.Code_nm as TransType,'' as TransSubType,Reason = '',Cons_shiptoId=isnull(Cons_ac.ac_id,0),Cons_LocId=''
--,ITC_Date=case when isnull(H.u_cldt,'')>1900 then isnull(H.u_cldt,'') else isnull(H.date,'') end
FROM CPMAIN H left outer join CPITEM D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) left outer JOIN IT_MAST IT ON (D .IT_CODE = IT.IT_CODE) LEFT OUTER JOIN ac_mast Cons_ac ON (h.Ac_id = Cons_ac.ac_id) LEFT OUTER JOIN lcode  ON (lcode.Entry_ty = h.Entry_ty) WHERE H.TDSPAYTYPE = 2 AND H.ENTRY_TY ='CP' AND (D.SGSRT_AMT + D.CGSRT_AMT + D.IGSRT_AMT + D.COMRPCESS ) > 0 AND (H.DATE BETWEEN @LStartDate AND @LEndDate) )AA
UPDATE A SET mCGST_PER = (CASE WHEN ISNULL(GSTRATE,0) > 0  AND (ISNULL(CGSRT_AMT,0) + ISNULL(CGST_AMT,0)) > 0 AND ISNULL(CGST_PER,0) = 0 THEN GSTRATE/2 ELSE CGST_PER END)
,mSGST_PER = (CASE WHEN ISNULL(GSTRATE,0) > 0  AND (ISNULL(SGSRT_AMT,0) + ISNULL(SGST_AMT,0)) > 0 AND ISNULL(SGST_PER,0) = 0 THEN GSTRATE/2 ELSE SGST_PER END)
,mIGST_PER = (CASE WHEN ISNULL(GSTRATE,0) > 0  AND (ISNULL(IGSRT_AMT,0) + ISNULL(IGST_AMT,0)) > 0 AND ISNULL(IGST_PER,0) = 0 THEN GSTRATE ELSE IGST_PER END) FROM #BankCash A
SELECT * INTO #BankCashTemp FROM (SELECT * FROM #BANKCASH Union all SELECT mCGST_PER=CAST(0 AS NUMERIC(7,2)),mSGST_PER=CAST(0 AS NUMERIC(7,2)),mIGST_PER=CAST(0 AS NUMERIC(7,2)),H.Entry_ty, H.Tran_cd,BC.Itserial, H.INV_NO, H.DATE,0 as IT_CODE,0 as QTY,d.Taxable AS Taxableamt,case when (ISNULL(D.CGST_AMT,0) + ISNULL(d.SGST_AMT,0)) > 0 THEN  (CASE WHEN ISNULL(D.TAXRATE,0)> 0 THEN (ISNULL(D.TAXRATE,0) / 2) ELSE 0 END  ) ELSE 0 END as CGST_PER,D.CGST_AMT,case when (ISNULL(D.CGST_AMT,0) + ISNULL(d.SGST_AMT,0)) > 0 THEN  (CASE WHEN ISNULL(D.TAXRATE,0)> 0
THEN (ISNULL(D.TAXRATE,0) / 2) ELSE 0 END )  ELSE 0 END as SGST_PER,D.SGST_AMT,case when (ISNULL(D.IGST_AMT,0)) > 0 THEN  (ISNULL(D.TAXRATE,0))  ELSE 0 END as IGST_PER,D.IGST_AMT,ORG_INVNO=BC.INV_NO, BC.DATE as ORG_DATE, 0 as CGSRT_AMT, 0 as SGSRT_AMT,0 as IGSRT_AMT ,0 as GRO_AMT,net_amt=(select SUM(isnull(Taxable,0)+isnull(cgst_amt,0)+isnull(SGST_AMT ,0)+isnull(IGST_AMT ,0)) from TaxAllocation  where entry_ty = h.entry_ty and Tran_cd =h.tran_cd) 	,replace(d.ccessrate,'SELECT','') as cessrate,d.compcess as cess_amt,0 as cessrt_amt
,'' as LineRule,'' as inv_sr,'' as l_yn,''  as uqc , ''as IT_NAME,'' AS Isservice, '' as HSNCODE,RevCharge = '','' as AGAINSTGS,AmendDate = '',Cons_ac_name =(case when buyer_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else  Cons_ac.ac_name end) else( case WHEN isnull(H.sAc_id, 0) > 0 then  buyer_sp.ac_name else  buyer_ac.ac_name end) end ),SUPP_TYPE =(case when buyer_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.SUPP_TYPE else Cons_ac.SUPP_TYPE end )
else( case WHEN isnull(H.sAc_id, 0) > 0 then  buyer_sp.SUPP_TYPE else  buyer_ac.SUPP_TYPE end) end ),buyer_SUPP_TYPE =(case WHEN isnull(H.sAc_id, 0) > 0 then  buyer_sp.SUPP_TYPE else  buyer_ac.SUPP_TYPE end),st_type =(case when buyer_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.st_type else  Cons_ac.st_type end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  buyer_sp.st_type else  buyer_ac.st_type end) end),buyer_st_type =(case WHEN isnull(H.sAc_id, 0) > 0 then  buyer_sp.st_type else  buyer_ac.st_type end)
,Cons_gstin = (case when buyer_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.GSTIN,'') = '' THEN Cons_sp.UID  ELSE Cons_sp.GSTIN END ) else (CASE WHEN ISNULL(Cons_ac.GSTIN,'') = '' THEN Cons_ac.UID  ELSE Cons_ac.GSTIN  END )end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(buyer_sp.GSTIN,'') = ''  then buyer_sp.UID else buyer_sp.GSTIN end ) else  (CASE WHEN ISNULL(buyer_ac.GSTIN,'')= '' THEN buyer_ac.UID ELSE buyer_ac.GSTIN END) end) end),buyer_gstin =(case WHEN isnull(H.sAc_id, 0) > 0
then  (CASE When isnull(buyer_sp.GSTIN,'') = ''  then buyer_sp.UID else buyer_sp.GSTIN end ) else  (CASE WHEN ISNULL(buyer_ac.GSTIN,'')= '' THEN buyer_ac.UID ELSE buyer_ac.GSTIN END) end),pos_std_cd =h.GSTSCODE,pos = h.gststate,Cons_pos =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.state else  Cons_ac.state end),buyer_pos =(case WHEN isnull(H.sAc_id, 0) > 0 then  buyer_sp.state else  buyer_ac.state  end),Cons_PANNO = Cons_ac.i_tax,buyer_PANNO = Cons_ac.i_tax,pinvno='' ,CAST('' as SMALLDATETIME) AS pinvdt,TRANSTATUS =0 ,gstype =  '' ,AVL_ITC = 0
,'' as beno,'' as bedt,0 as GSTRATE,'' as portcode,PaymentType ='Advance Adjustment','' as TransType,'' as TransSubType,Reason = '',Cons_shiptoId=isnull(buyer_sp.shipto_id,0),Cons_LocId=Isnull(buyer_sp.Location_Id,'')
--,ITC_Date=case when isnull(H.u_cldt,'')>1900 then isnull(H.u_cldt,'') else isnull(H.date,'') end
FROM PTMAIN  H INNER JOIN TaxAllocation D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) LEFT OUTER JOIN #BANKCASH BC ON (BC.ENTRY_TY = D.RENTRY_TY AND BC.TRAN_CD = D.ITREF_TRAN) INNER JOIN shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id ) LEFT OUTER JOIN ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id) LEFT OUTER JOIN shipto buyer_sp ON (buyer_sp.ac_id = h.Ac_id and buyer_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN ac_mast buyer_ac ON (h.Ac_id = buyer_ac.ac_id)  where  H.entry_ty = 'PT' AND (h.DATE BETWEEN @LStartDate AND @LEndDate)
Union all
SELECT mCGST_PER=CAST(0 AS NUMERIC(7,2)),mSGST_PER=CAST(0 AS NUMERIC(7,2)),mIGST_PER=CAST(0 AS NUMERIC(7,2)),H.Entry_ty, H.Tran_cd,BC.Itserial, H.INV_NO, H.DATE,0 as IT_CODE,0 as QTY,d.Taxable AS Taxableamt,case when (ISNULL(D.CGST_AMT,0) + ISNULL(d.SGST_AMT,0)) > 0 THEN  (CASE WHEN ISNULL(D.TAXRATE,0)> 0 THEN (ISNULL(D.TAXRATE,0) / 2) ELSE 0 END  ) ELSE 0 END as CGST_PER,D.CGST_AMT,case when (ISNULL(D.CGST_AMT,0) + ISNULL(d.SGST_AMT,0)) > 0 THEN  (CASE WHEN ISNULL(D.TAXRATE,0)> 0 THEN (ISNULL(D.TAXRATE,0) / 2) ELSE 0 END )  ELSE 0 END as SGST_PER,D.SGST_AMT
,case when (ISNULL(D.IGST_AMT,0)) > 0 THEN  (ISNULL(D.TAXRATE,0))  ELSE 0 END as IGST_PER,D.IGST_AMT,ORG_INVNO=BC.INV_NO, BC.DATE as ORG_DATE, 0 as CGSRT_AMT, 0 as SGSRT_AMT,0 as IGSRT_AMT ,0 as GRO_AMT,net_amt=(select SUM(isnull(Taxable,0)+isnull(cgst_amt,0)+isnull(SGST_AMT ,0)+isnull(IGST_AMT ,0)) from TaxAllocation  where entry_ty = h.entry_ty and Tran_cd =h.tran_cd) 	,replace(d.ccessrate,'SELECT','') as cessrate,d.compcess as cess_amt,0 as cessrt_amt,'' as LineRule,'' as inv_sr,'' as l_yn,''  as uqc , ''as IT_NAME,'' AS Isservice, '' as HSNCODE
,RevCharge = '','' as AGAINSTGS,AmendDate = '',Cons_ac_name =(case when buyer_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.mailname else  Cons_ac.ac_name end) else( case WHEN isnull(H.sAc_id, 0) > 0 then  buyer_sp.ac_name else  buyer_ac.ac_name end) end ),SUPP_TYPE =(case when buyer_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.SUPP_TYPE else Cons_ac.SUPP_TYPE end ) else( case WHEN isnull(H.sAc_id, 0) > 0 then  buyer_sp.SUPP_TYPE else  buyer_ac.SUPP_TYPE end) end )
,buyer_SUPP_TYPE =(case WHEN isnull(H.sAc_id, 0) > 0 then  buyer_sp.SUPP_TYPE else  buyer_ac.SUPP_TYPE end),st_type =(case when buyer_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.st_type else  Cons_ac.st_type end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  buyer_sp.st_type else  buyer_ac.st_type end) end),buyer_st_type =(case WHEN isnull(H.sAc_id, 0) > 0 then  buyer_sp.st_type else  buyer_ac.st_type end),Cons_gstin = (case when buyer_ac.i_tax=Cons_ac.i_tax then (case WHEN isnull(H.scons_id, 0) > 0 then (CASE WHEN ISNULL(Cons_sp.GSTIN,'') = ''
THEN Cons_sp.UID  ELSE Cons_sp.GSTIN END ) else (CASE WHEN ISNULL(Cons_ac.GSTIN,'') = '' THEN Cons_ac.UID  ELSE Cons_ac.GSTIN  END )end) else (case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(buyer_sp.GSTIN,'') = ''  then buyer_sp.UID else buyer_sp.GSTIN end ) else  (CASE WHEN ISNULL(buyer_ac.GSTIN,'')= '' THEN buyer_ac.UID ELSE buyer_ac.GSTIN END) end) end),buyer_gstin =(case WHEN isnull(H.sAc_id, 0) > 0 then  (CASE When isnull(buyer_sp.GSTIN,'') = ''  then buyer_sp.UID else buyer_sp.GSTIN end ) else  (CASE WHEN ISNULL(buyer_ac.GSTIN,'')= '' THEN buyer_ac.UID ELSE buyer_ac.GSTIN END) end)
,pos_std_cd =h.GSTSCODE,pos = h.gststate,Cons_pos =(case WHEN isnull(H.scons_id, 0) > 0 then  Cons_sp.state else  Cons_ac.state end),buyer_pos =(case WHEN isnull(H.sAc_id, 0) > 0 then  buyer_sp.state else  buyer_ac.state  end),Cons_PANNO = Cons_ac.i_tax,buyer_PANNO = Cons_ac.i_tax,pinvno='' ,CAST('' as SMALLDATETIME) AS pinvdt,TRANSTATUS =0 ,gstype =  '' ,AVL_ITC = 0,'' as beno,'' as bedt ,0 as GSTRATE,'' as portcode,PaymentType ='Advance Adjustment','' as TransType,'' as TransSubType,Reason = '',Cons_shiptoId=isnull(buyer_sp.shipto_id,0),Cons_LocId=Isnull(buyer_sp.Location_Id,'')
--,ITC_Date=case when isnull(H.u_cldt,'')>1900 then isnull(H.u_cldt,'') else isnull(H.date,'') end
FROM EPMAIN H INNER JOIN TaxAllocation D ON (H.ENTRY_TY = D .ENTRY_TY AND H.TRAN_CD = D .TRAN_CD) LEFT OUTER JOIN #BANKCASH BC ON (BC.ENTRY_TY = D.RENTRY_TY AND BC.TRAN_CD = D.ITREF_TRAN) INNER JOIN shipto Cons_sp ON (Cons_sp.ac_id = h.Cons_id and Cons_sp.shipto_id = h.scons_id ) LEFT OUTER JOIN ac_mast Cons_ac ON (h.cons_id = Cons_ac.ac_id) LEFT OUTER JOIN shipto buyer_sp ON (buyer_sp.ac_id = h.Ac_id and buyer_sp.shipto_id = h.sAc_id) LEFT OUTER JOIN ac_mast buyer_ac ON (h.Ac_id = buyer_ac.ac_id) where  H.entry_ty = 'E1' AND (h.DATE BETWEEN @LStartDate AND @LEndDate)) BB Order by date,inv_No
UPDATE A SET mCGST_PER = (CASE WHEN ISNULL(GSTRATE,0) > 0  AND (ISNULL(CGSRT_AMT,0) + ISNULL(CGST_AMT,0)) > 0 AND ISNULL(CGST_PER,0) = 0 THEN GSTRATE/2 ELSE CGST_PER END)
,mSGST_PER = (CASE WHEN ISNULL(GSTRATE,0) > 0  AND (ISNULL(SGSRT_AMT,0) + ISNULL(SGST_AMT,0)) > 0 AND ISNULL(SGST_PER,0) = 0 THEN GSTRATE/2 ELSE SGST_PER END)
,mIGST_PER = (CASE WHEN ISNULL(GSTRATE,0) > 0  AND (ISNULL(IGSRT_AMT,0) + ISNULL(IGST_AMT,0)) > 0 AND ISNULL(IGST_PER,0) = 0 THEN GSTRATE ELSE IGST_PER END) FROM #BankCashTemp A
SELECT * FROM #BankCashTemp
Drop table #BankCashTemp Drop table #BankCash